#!/usr/bin/env python3
"""Generate tema/cifre.tex from _surse/cifre.json.

cifre.json is the single source of numbers for every VestVentures document.
This script turns it into LaTeX lookups so a .tex file never types a model
number by hand:

    \\cf{base.mrr_m36_eur}    -> 15,761      (formatted, thousands separator)
    \\cfn{base.mrr_m36_eur}   -> 15761       (raw, for TikZ / pgfmath)
    \\cfk{round_eur}          -> 250         (thousands, max 1 decimal)
    \\cfm{pre_money_eur}      -> 1.25        (millions, max 2 decimals)
    \\cfK{tam_sam_som.som.eur_arr} -> 189     (thousands, whole)
    \\cfM{tam_sam_som.tam.eur_year} -> 188    (millions, max 1 decimal)
    \\cfKa{base.cash_m36_eur}      -> 50      (absolute value, thousands, whole)
    \\cfp{unit_economics.ltv_cac}{2}         -> 3.20   (fixed decimals: 0, 1 or 2)
    \\cfkd{conservative.mrr_m24_eur}           -> 2.0    (thousands, always 1 decimal)

Rounding is half-up on the decimal value (Decimal(str(v))), never Python's
round(), which rounds half to even on binary floats (1.25 -> "1.2").

Keys are the JSON path joined with dots; list items use their index
(`use_of_funds.0.eur`, `round_size_test.4.runway_plan_months`).
An unknown key stops the compilation with an error instead of printing
nothing.

Run:  python3 tema/cifre_tex.py      (from /srv/apps/ERP/vestventures)
"""
import json
import pathlib
from decimal import ROUND_HALF_UP, Decimal

RADACINA = pathlib.Path(__file__).resolve().parent.parent
SURSA = RADACINA / "_surse" / "cifre.json"
TINTA = RADACINA / "tema" / "cifre.tex"

SPECIALE = {"\\": r"\textbackslash{}", "&": r"\&", "%": r"\%", "$": r"\$",
            "#": r"\#", "_": r"\_", "{": r"\{", "}": r"\}", "~": r"\textasciitilde{}",
            "^": r"\textasciicircum{}", "€": r"\euro{}"}


def tex(s: str) -> str:
    return "".join(SPECIALE.get(c, c) for c in s)


def fmt_num(v) -> str:
    if isinstance(v, bool):
        return str(v).lower()
    if isinstance(v, int):
        return f"{v:,}"
    if isinstance(v, float):
        if v.is_integer():
            return f"{int(v):,}"
        ent, zec = repr(v).split(".")
        return f"{int(ent):,}.{zec}"
    return tex(str(v))


def rotunjit(v, impartitor: int, zecimale: int) -> Decimal:
    pas = Decimal(1).scaleb(-zecimale)
    return (Decimal(str(v)) / Decimal(impartitor)).quantize(pas, rounding=ROUND_HALF_UP)


def fix(v, impartitor: int, zecimale: int) -> str:
    """Fixed number of decimals, thousands separator: 37.4 -> '37.40'."""
    return f"{rotunjit(v, impartitor, zecimale):,.{zecimale}f}"


def scurt(v, impartitor: int, zecimale: int) -> str:
    """At most `zecimale` decimals, trailing zeros dropped: 1.25 -> '1.25', 0.25 -> '0.25'."""
    s = fix(v, impartitor, zecimale)
    if "." in s:
        s = s.rstrip("0").rstrip(".")
    return s


def aplatizeaza(o, prefix=""):
    if isinstance(o, dict):
        for k, v in o.items():
            if k.startswith("_"):
                continue
            yield from aplatizeaza(v, f"{prefix}.{k}" if prefix else k)
    elif isinstance(o, list):
        for i, v in enumerate(o):
            yield from aplatizeaza(v, f"{prefix}.{i}")
    else:
        yield prefix, o


def main() -> None:
    date = json.loads(SURSA.read_text(encoding="utf-8"))
    linii = [
        "% =====================================================================",
        "%  GENERATED by tema/cifre_tex.py from _surse/cifre.json -- do not edit.",
        f"%  cifre.json generated: {date.get('_meta', {}).get('generated', '?')}",
        "% =====================================================================",
        r"\makeatletter",
        r"\newcommand{\cf@get}[2]{\ifcsname cf#1@#2\endcsname\csname cf#1@#2\endcsname"
        r"\else\errmessage{cifre.tex: unknown key '#2'}\fi}",
        r"\newcommand{\cf}[1]{\cf@get{f}{#1}}",
        r"\newcommand{\cfn}[1]{\cf@get{n}{#1}}",
        r"\newcommand{\cfk}[1]{\cf@get{k}{#1}}",
        r"\newcommand{\cfm}[1]{\cf@get{m}{#1}}",
        r"\newcommand{\cfK}[1]{\cf@get{K}{#1}}",
        r"\newcommand{\cfM}[1]{\cf@get{M}{#1}}",
        r"\newcommand{\cfKa}[1]{\cf@get{Ka}{#1}}",
        r"\newcommand{\cfp}[2]{\cf@get{p#2}{#1}}",
        r"\newcommand{\cfkd}[1]{\cf@get{kd}{#1}}",
    ]
    for cheie, v in aplatizeaza(date):
        if v is None:
            v = "n/a"
        linii.append(rf"\expandafter\def\csname cff@{cheie}\endcsname{{{fmt_num(v)}}}")
        if isinstance(v, (int, float)) and not isinstance(v, bool):
            linii.append(rf"\expandafter\def\csname cfn@{cheie}\endcsname{{{v}}}")
            linii.append(rf"\expandafter\def\csname cfk@{cheie}\endcsname{{{scurt(v, 1000, 1)}}}")
            linii.append(rf"\expandafter\def\csname cfm@{cheie}\endcsname{{{scurt(v, 1_000_000, 2)}}}")
            linii.append(rf"\expandafter\def\csname cfK@{cheie}\endcsname{{{scurt(v, 1000, 0)}}}")
            linii.append(rf"\expandafter\def\csname cfM@{cheie}\endcsname{{{scurt(v, 1_000_000, 1)}}}")
            linii.append(rf"\expandafter\def\csname cfKa@{cheie}\endcsname{{{scurt(abs(v), 1000, 0)}}}")
            for z in (0, 1, 2):
                linii.append(rf"\expandafter\def\csname cfp{z}@{cheie}\endcsname{{{fix(v, 1, z)}}}")
            linii.append(rf"\expandafter\def\csname cfkd@{cheie}\endcsname{{{fix(v, 1000, 1)}}}")
    linii.append(r"\makeatother")
    TINTA.write_text("\n".join(linii) + "\n", encoding="utf-8")
    print(f"wrote {TINTA} ({len(linii)} lines)")


if __name__ == "__main__":
    main()
