// src/lib/asistent/destinatii.ts
/**
 * Lista ÎNCHISĂ de locuri către care asistentul are voie să trimită.
 *
 * Ăsta e mecanismul care face imposibilă halucinația de link, și merită spus de
 * ce nu e o chestiune de prompt. Un model căruia i se cere „scrie adresa paginii"
 * va scrie `/pontaj/orele-mele` — sună exact ca o rută a acestei aplicații, nu e
 * o invenție absurdă, și e un 404. Nicio formulare fermă din promptul de sistem
 * nu elimină clasa asta de greșeli; ea dispare abia când modelul nu mai are
 * ocazia să scrie o adresă.
 *
 * Aici modelul primește doar `id`-uri și poate emite doar `[[ruta:<id>]]`.
 * Href-ul, eticheta, iconița și drumul de click le desenează aplicația, din
 * datele de mai jos. Un `id` care nu există se aruncă la randare
 * (`marcaje.ts`), deci cel mai rău lucru care se poate întâmpla e o referință
 * lipsă — niciodată una greșită.
 *
 * ── DE CE E SCRISĂ DE MÂNĂ, ȘI NU GENERATĂ ───────────────────────────────────
 * Rutele se pot enumera mecanic din `src/app/**​/page.tsx`, iar `permission` se
 * poate ghici din `can(...)`-ul din capul fiecărei pagini. Ce NU se poate genera
 * e `descriere`: „ce faci pe ecranul ăsta, spus unui om care nu știe unde e".
 * Aia e conținutul propriu-zis al asistentului, și e singurul motiv pentru care
 * el e mai util decât paleta Cmd+K, care are deja căutare pe etichete.
 *
 * Împotriva îmbătrânirii tăcute stă `destinatii.test.ts`: parcurge arborele de
 * rute de pe disc și cere ca fiecare rută statică să fie ori aici, ori în
 * `EXCLUSE` cu motiv scris. Exact tiparul lui `permissions.test.ts`, care
 * compară codul cu seed-ul SQL. Fără poarta aia, fișierul devine în trei luni
 * `docs/conturi-si-rute.md`: două rute documentate care nu există și
 * unsprezece existente nedocumentate.
 *
 * ── PERMISIUNILE DE AICI SUNT PORȚI DE INTRARE, NU DE ACȚIUNE ────────────────
 * `permission` + `minScope` sunt cele care decid dacă pagina se deschide sau
 * întoarce `AccesRestricționat` — citite din porțile reale ale paginilor, nu din
 * documentație. Butoanele dinăuntru cer adesea mai mult (`/pontaj` se deschide
 * cu `attendance:read` own, dar aprobarea cere `approve` team); asta nu ne
 * privește aici, fiindcă asistentul trimite spre ecran, nu apasă butoane.
 *
 * Unde nav-ul declară un prag mai strict decât pagina, se ia al nav-ului. La
 * îndoială se alege VARIANTA STRICTĂ: o destinație ascunsă degeaba e o pierdere
 * mică, una oferită și apoi refuzată e chiar defectul pe care fișierul ăsta
 * există ca să-l prevină.
 */
import type { FeatureKey } from "@/config/features";
import type { MinScope, PermissionKey } from "@/config/permissions";
import { NAV_GROUPS, NAV_ITEMS, PORTAL_NAV_GROUPS, PORTAL_NAV_ITEMS } from "@/config/navigation";

export type ZonaAsistent = "app" | "portal";

/** Datele scrise de mână. `drum` lipsește: se calculează. */
type Intrare = Readonly<{
  id: string;
  href: string;
  eticheta: string;
  zona: ZonaAsistent;
  /** `id`-ul intrării de meniu sub care stă ruta. `null` doar pentru rădăcini. */
  parinte: string | null;
  /** Eticheta filei din banda paginii, când se ajunge printr-o filă. */
  fila: string | null;
  featureKey: FeatureKey | null;
  permission: PermissionKey | null;
  minScope: MinScope;
  descriere: string;
}>;

export type Destinatie = Intrare &
  Readonly<{
    /** Drumul de click, gata de citit: ["Operațiuni", "Pontaj", "Perioade"]. */
    drum: readonly string[];
  }>;

/*
 * Rutele care NU intră în index, cu motivul. Testul de drift le cere explicit,
 * ca „lipsește" să nu poată fi confundat cu „am uitat".
 */
export const EXCLUSE: Readonly<Record<string, string>> = {
  "/portal/instalare":
    "Se ajunge la ea din banda de instalare a portalului, nu prin navigare; a trimite pe cineva acolo din senin n-are înțeles.",
};

const INTRARI: readonly Intrare[] = [
  // ── Nucleu ─────────────────────────────────────────────────────────────────
  {
    id: "panou",
    href: "/panou",
    eticheta: "Panou de control",
    zona: "app",
    parinte: null,
    fila: null,
    featureKey: null,
    permission: null,
    minScope: "own",
    descriere:
      "Cifrele zilei, ce așteaptă semnătura ta și scadențele apropiate. Prima pagină după autentificare.",
  },
  {
    id: "notificari",
    href: "/notificari",
    eticheta: "Notificări",
    zona: "app",
    parinte: null,
    fila: null,
    featureKey: null,
    permission: null,
    minScope: "own",
    descriere: "Toate notificările primite, fiecare cu legătură către ce a produs-o.",
  },
  {
    id: "profil",
    href: "/profil",
    eticheta: "Profilul meu",
    zona: "app",
    parinte: null,
    fila: null,
    featureKey: null,
    permission: null,
    minScope: "own",
    descriere: "Datele contului tău: nume, e-mail, parolă.",
  },

  // ── Pontaj ─────────────────────────────────────────────────────────────────
  {
    id: "pontaj",
    href: "/pontaj",
    eticheta: "Prezența",
    zona: "app",
    parinte: "pontaj",
    fila: "Prezența",
    featureKey: "attendance",
    permission: "attendance:read",
    minScope: "own",
    descriere:
      "Prezența înregistrată, în trei vizualizări: săptămâna pe ore, luna ca un calendar sau foaia colectivă. De aici se completează orele lucrate.",
  },
  {
    id: "pontaj.saptamana",
    href: "/pontaj/saptamana",
    eticheta: "Planul săptămânii",
    zona: "app",
    parinte: "pontaj",
    fila: "Planul săptămânii",
    featureKey: "attendance",
    permission: "attendance:create",
    minScope: "own",
    descriere:
      "Orele planificate pe zilele săptămânii, trimise apoi într-un singur pas spre aprobare.",
  },
  {
    id: "pontaj.perioade",
    href: "/pontaj/perioade",
    eticheta: "Perioade de pontaj",
    zona: "app",
    parinte: "pontaj",
    fila: "Perioade",
    featureKey: "attendance",
    permission: "attendance:read",
    minScope: "own",
    descriere:
      "Perioadele lunare de pontaj: se deschid la început de lună, se aprobă în loturi și se blochează la final.",
  },
  {
    id: "pontaj.aprobare",
    href: "/pontaj/aprobare",
    eticheta: "Aprobare pontaj",
    zona: "app",
    parinte: "pontaj",
    fila: "Aprobare",
    featureKey: "attendance",
    permission: "attendance:approve",
    minScope: "team",
    descriere: "Pontajele echipei care așteaptă decizia ta, aprobabile în lot.",
  },
  {
    id: "pontaj.setari",
    href: "/pontaj/setari",
    eticheta: "Pontarea",
    zona: "app",
    parinte: "pontaj",
    fila: "Setări",
    featureKey: "attendance",
    permission: "attendance:update",
    minScope: "all",
    descriere:
      "Cum se pontează: ceasul de pe telefon, codul punctului de lucru, ce verificare se cere la pontare.",
  },
  {
    id: "pontaj.setari.reguli",
    href: "/pontaj/setari/reguli",
    eticheta: "Regulile de timp",
    zona: "app",
    parinte: "pontaj",
    fila: "Setări → Regulile de timp",
    featureKey: "attendance",
    permission: "attendance:update",
    minScope: "all",
    descriere: "Durata maximă a unei zile de lucru, pauza minimă de repaus și rotunjirile.",
  },

  // ── Concedii ───────────────────────────────────────────────────────────────
  {
    id: "concedii",
    href: "/concedii",
    eticheta: "Cererile de concediu",
    zona: "app",
    parinte: "concedii",
    fila: "Cererile mele",
    featureKey: "leave",
    permission: "leave:read",
    minScope: "own",
    descriere:
      "Cererile de concediu — ale tale, iar cu drepturi de echipă și ale celorlalți. De aici se depune o cerere nouă.",
  },
  {
    id: "concedii.sold",
    href: "/concedii/sold",
    eticheta: "Soldul de concediu",
    zona: "app",
    parinte: "concedii",
    fila: "Soldul meu",
    featureKey: "leave",
    permission: "leave:read",
    minScope: "own",
    descriere: "Câte zile ți se cuvin pe anul curent, câte ai consumat și câte îți mai rămân.",
  },
  {
    id: "concedii.aprobari",
    href: "/concedii/aprobari",
    eticheta: "Aprobări de concediu",
    zona: "app",
    parinte: "concedii",
    fila: "Aprobări",
    featureKey: "leave",
    permission: "leave:approve",
    minScope: "team",
    descriere: "Cererile de concediu care așteaptă decizia ta.",
  },
  {
    id: "concedii.echipa",
    href: "/concedii/echipa",
    eticheta: "Concediile echipei",
    zona: "app",
    parinte: "concedii",
    fila: "Echipa",
    featureKey: "leave",
    permission: "leave:read",
    minScope: "team",
    descriere: "Concediile oamenilor din echipa ta, ca listă.",
  },
  {
    id: "concedii.calendar",
    href: "/concedii/calendar",
    eticheta: "Calendarul de concedii",
    zona: "app",
    parinte: "concedii",
    fila: null,
    featureKey: "leave",
    permission: "leave:read",
    minScope: "team",
    descriere: "Cine lipsește și când, pe luni — pentru a vedea suprapunerile înainte de aprobare.",
  },
  {
    id: "concedii.setari",
    href: "/concedii/setari",
    eticheta: "Setări concedii",
    zona: "app",
    parinte: "concedii",
    fila: null,
    featureKey: "leave",
    permission: "leave:update",
    minScope: "all",
    descriere: "Tipurile de concediu, zilele acordate pe fiecare și regulile de aprobare.",
  },

  // ── Angajați și structură ──────────────────────────────────────────────────
  {
    id: "angajati",
    href: "/angajati",
    eticheta: "Angajați",
    zona: "app",
    parinte: "angajati",
    fila: null,
    featureKey: null,
    permission: "employees:read",
    minScope: "team",
    descriere:
      "Lista angajaților, cu căutare și filtre. De aici se intră pe fișa fiecăruia: date, contract, documente.",
  },
  {
    id: "angajati.nou",
    href: "/angajati/nou",
    eticheta: "Înrolare angajat",
    zona: "app",
    parinte: "angajati",
    fila: null,
    featureKey: null,
    permission: "employees:create",
    minScope: "own",
    descriere: "Adăugarea unui angajat nou, pas cu pas: identitate, contract, încadrare.",
  },
  {
    id: "angajati.import",
    href: "/angajati/import",
    eticheta: "Import din Excel",
    zona: "app",
    parinte: "angajati",
    fila: null,
    featureKey: null,
    permission: "employees:create",
    minScope: "own",
    descriere: "Adăugarea mai multor angajați deodată, dintr-un fișier Excel.",
  },
  {
    id: "angajati.sabloane",
    href: "/angajati/sabloane-documente",
    eticheta: "Șabloane de documente",
    zona: "app",
    parinte: "angajati",
    fila: null,
    featureKey: null,
    permission: "employees:update",
    minScope: "all",
    descriere: "Textele din care se generează adeverințe, decizii și acte adiționale.",
  },
  {
    id: "organigrama",
    href: "/organigrama",
    eticheta: "Organigramă",
    zona: "app",
    parinte: "organigrama",
    fila: null,
    featureKey: null,
    permission: "employees:read",
    minScope: "own",
    descriere: "Structura firmei ca arbore: cine raportează cui.",
  },
  {
    id: "departamente",
    href: "/departamente",
    eticheta: "Departamente",
    zona: "app",
    parinte: "departamente",
    fila: null,
    featureKey: null,
    permission: "departments:read",
    minScope: "own",
    descriere: "Departamentele firmei, șefii lor și oamenii din fiecare.",
  },
  {
    id: "puncte-lucru",
    href: "/puncte-lucru",
    eticheta: "Puncte de lucru",
    zona: "app",
    parinte: "puncte-lucru",
    fila: null,
    featureKey: null,
    permission: "departments:read",
    minScope: "own",
    descriere: "Punctele de lucru, cu adresele și codurile lor de pontare.",
  },

  // ── REGES-Online ───────────────────────────────────────────────────────────
  {
    id: "reges",
    href: "/reges",
    eticheta: "Registrul REGES",
    zona: "app",
    parinte: "reges",
    fila: "Registru",
    featureKey: "reges",
    permission: "reges:read",
    minScope: "all",
    descriere:
      "Ce s-a transmis la Inspecția Muncii, ce a fost acceptat și ce a fost respins, cu motivul.",
  },
  {
    id: "reges.propuneri",
    href: "/reges/propuneri",
    eticheta: "Propuneri de detașare",
    zona: "app",
    parinte: "reges",
    fila: "Propuneri detașare",
    featureKey: "reges",
    permission: "reges:read",
    minScope: "all",
    descriere: "Propunerile de detașare și mutare primite prin REGES, de acceptat sau refuzat.",
  },
  {
    id: "reges.setari",
    href: "/reges/setari",
    eticheta: "Chei API REGES",
    zona: "app",
    parinte: "reges",
    fila: "Chei API",
    featureKey: "reges",
    permission: "reges:configure",
    minScope: "all",
    descriere: "Legătura cu REGES-Online: credențialele firmei pentru transmisie.",
  },

  // ── Evaluări ───────────────────────────────────────────────────────────────
  {
    id: "evaluari",
    href: "/evaluari",
    eticheta: "Evaluări",
    zona: "app",
    parinte: "evaluari",
    fila: "Evaluări",
    featureKey: "evaluations",
    permission: "evaluations:read",
    minScope: "team",
    descriere: "Evaluările de performanță în desfășurare și cele încheiate.",
  },
  {
    id: "evaluari.sabloane",
    href: "/evaluari/sabloane",
    eticheta: "Șabloane de evaluare",
    zona: "app",
    parinte: "evaluari",
    fila: "Șabloane",
    featureKey: "evaluations",
    permission: "evaluations:read",
    minScope: "team",
    descriere: "Grilele de evaluare, reutilizabile de la un ciclu la altul.",
  },

  // ── Integrare angajați ─────────────────────────────────────────────────────
  {
    id: "onboarding",
    href: "/onboarding",
    eticheta: "Parcursuri de integrare",
    zona: "app",
    parinte: "onboarding",
    fila: "Instanțe",
    featureKey: "onboarding",
    permission: "checklists:read",
    minScope: "own",
    descriere: "Parcursurile de integrare pornite pentru angajații noi și stadiul fiecăruia.",
  },
  {
    id: "onboarding.noua",
    href: "/onboarding/noua",
    eticheta: "Parcurs nou",
    zona: "app",
    parinte: "onboarding",
    fila: null,
    featureKey: "onboarding",
    permission: "checklists:create",
    minScope: "all",
    descriere: "Pornirea unui parcurs de integrare pentru un angajat, dintr-un șablon.",
  },
  {
    id: "onboarding.sabloane",
    href: "/onboarding/sabloane",
    eticheta: "Șabloane de checklist",
    zona: "app",
    parinte: "onboarding",
    fila: "Șabloane",
    featureKey: "onboarding",
    permission: "checklists:read",
    minScope: "own",
    descriere: "Șabloanele din care se pornesc parcursurile de integrare.",
  },
  {
    id: "onboarding.sabloane.nou",
    href: "/onboarding/sabloane/nou",
    eticheta: "Șablon de integrare nou",
    zona: "app",
    parinte: "onboarding",
    fila: null,
    featureKey: "onboarding",
    permission: "checklists:create",
    minScope: "all",
    descriere: "Un parcurs de integrare nou, cu sarcinile și responsabilii lui.",
  },
  {
    id: "onboarding.sarcini",
    href: "/onboarding/sarcinile-mele",
    eticheta: "Sarcinile mele de integrare",
    zona: "app",
    parinte: "onboarding",
    fila: "Sarcinile mele",
    featureKey: "onboarding",
    permission: "checklists:read",
    minScope: "own",
    descriere: "Pașii de integrare care îți revin ție, din parcursurile altora.",
  },

  // ── Cursuri ────────────────────────────────────────────────────────────────
  {
    id: "cursuri",
    href: "/cursuri",
    eticheta: "Cursuri",
    zona: "app",
    parinte: "cursuri",
    fila: "Cursuri",
    featureKey: "courses",
    permission: "courses:read",
    minScope: "team",
    descriere: "Cursurile firmei, cu lecțiile, testele și stadiul fiecăruia.",
  },
  {
    id: "cursuri.nou",
    href: "/cursuri/nou",
    eticheta: "Curs nou",
    zona: "app",
    parinte: "cursuri",
    fila: null,
    featureKey: "courses",
    permission: "courses:create",
    minScope: "team",
    descriere: "Un curs nou, construit din materialele bibliotecii.",
  },
  {
    id: "cursuri.biblioteca",
    href: "/cursuri/biblioteca",
    eticheta: "Bibliotecă de materiale",
    zona: "app",
    parinte: "cursuri",
    fila: "Bibliotecă",
    featureKey: "courses",
    permission: "courses:read",
    minScope: "team",
    descriere: "Materialele de curs: documente, prezentări, înregistrări.",
  },
  {
    id: "cursuri.biblioteca.nou",
    href: "/cursuri/biblioteca/nou",
    eticheta: "Material nou",
    zona: "app",
    parinte: "cursuri",
    fila: null,
    featureKey: "courses",
    permission: "courses:create",
    minScope: "team",
    descriere: "Adăugarea unui material în bibliotecă.",
  },
  {
    id: "cursuri.conformitate",
    href: "/cursuri/conformitate",
    eticheta: "Conformitate cursuri",
    zona: "app",
    parinte: "cursuri",
    fila: "Conformitate",
    featureKey: "courses",
    permission: "courses:read",
    minScope: "team",
    descriere: "Cine a parcurs ce curs, cine e restant și cui expiră certificarea.",
  },

  // ── SSM și PSI ─────────────────────────────────────────────────────────────
  {
    id: "ssm",
    href: "/ssm",
    eticheta: "Panoul SSM și PSI",
    zona: "app",
    parinte: "ssm",
    fila: "Panou",
    featureKey: "ssm",
    permission: "ssm:read",
    minScope: "own",
    descriere: "Scadențele apropiate și restanțele pe securitatea muncii și PSI.",
  },
  {
    id: "ssm.instruiri",
    href: "/ssm/instruiri",
    eticheta: "Instruiri",
    zona: "app",
    parinte: "ssm",
    fila: "Instruiri",
    featureKey: "ssm",
    permission: "ssm:read",
    minScope: "team",
    descriere:
      "Instruirile de securitate: cine, când, pe ce temă, cu semnătura de luare la cunoștință.",
  },
  {
    id: "ssm.instruiri.noua",
    href: "/ssm/instruiri/noua",
    eticheta: "Instruire nouă",
    zona: "app",
    parinte: "ssm",
    fila: null,
    featureKey: "ssm",
    permission: "ssm:create",
    minScope: "team",
    descriere: "Înregistrarea unei instruiri, pentru unul sau mai mulți angajați.",
  },
  {
    id: "ssm.medicina",
    href: "/ssm/medicina-muncii",
    eticheta: "Medicina muncii",
    zona: "app",
    parinte: "ssm",
    fila: "Medicina muncii",
    featureKey: "ssm",
    permission: "ssm:read",
    minScope: "team",
    descriere: "Fișele de aptitudine, cu data controlului și scadența următorului.",
  },
  {
    id: "ssm.medicina.noua",
    href: "/ssm/medicina-muncii/noua",
    eticheta: "Fișă de aptitudine nouă",
    zona: "app",
    parinte: "ssm",
    fila: null,
    featureKey: "ssm",
    permission: "ssm:create",
    minScope: "team",
    descriere: "Înregistrarea unei fișe de aptitudine primite de la medicina muncii.",
  },
  {
    id: "ssm.eip",
    href: "/ssm/eip",
    eticheta: "Echipament de protecție",
    zona: "app",
    parinte: "ssm",
    fila: "EIP",
    featureKey: "ssm",
    permission: "ssm:read",
    minScope: "team",
    descriere: "Echipamentul individual de protecție predat fiecăruia și când trebuie înlocuit.",
  },
  {
    id: "ssm.autorizatii",
    href: "/ssm/autorizatii",
    eticheta: "Autorizații nominale",
    zona: "app",
    parinte: "ssm",
    fila: "Autorizații nominale",
    featureKey: "ssm",
    permission: "ssm:read",
    minScope: "team",
    descriere: "Autorizațiile pe persoană — ISCIR, electrician și celelalte — cu expirările lor.",
  },
  {
    id: "ssm.accidente",
    href: "/ssm/accidente",
    eticheta: "Accidente de muncă",
    zona: "app",
    parinte: "ssm",
    fila: "Accidente",
    featureKey: "ssm",
    permission: "ssm:read",
    minScope: "team",
    descriere: "Accidentele de muncă înregistrate, cu cercetarea și comunicarea lor.",
  },
  {
    id: "ssm.accidente.nou",
    href: "/ssm/accidente/nou",
    eticheta: "Accident nou",
    zona: "app",
    parinte: "ssm",
    fila: null,
    featureKey: "ssm",
    permission: "ssm:create",
    minScope: "team",
    descriere: "Înregistrarea unui accident de muncă.",
  },
  {
    id: "ssm.stingatoare",
    href: "/ssm/stingatoare",
    eticheta: "Stingătoare",
    zona: "app",
    parinte: "ssm",
    fila: "Stingătoare",
    featureKey: "ssm",
    permission: "ssm:read",
    minScope: "team",
    descriere: "Stingătoarele din dotare, cu verificările periodice și scadențele lor.",
  },
  {
    id: "ssm.stingatoare.nou",
    href: "/ssm/stingatoare/nou",
    eticheta: "Stingător nou",
    zona: "app",
    parinte: "ssm",
    fila: null,
    featureKey: "ssm",
    permission: "ssm:create",
    minScope: "team",
    descriere: "Adăugarea unui stingător în evidență.",
  },

  // ── Parc auto ──────────────────────────────────────────────────────────────
  {
    id: "flota",
    href: "/flota",
    eticheta: "Vehicule",
    zona: "app",
    parinte: "flota",
    fila: "Vehicule",
    featureKey: "fleet",
    permission: "vehicles:read",
    minScope: "own",
    descriere: "Vehiculele firmei, cu documentele lor — ITP, RCA, rovinietă — și scadențele.",
  },
  {
    id: "flota.foi",
    href: "/flota/foi",
    eticheta: "Foi de parcurs",
    zona: "app",
    parinte: "flota",
    fila: "Foi de parcurs",
    featureKey: "fleet",
    permission: "trip_sheets:read",
    minScope: "own",
    descriere: "Foile de parcurs: curse, kilometri parcurși și combustibilul consumat.",
  },
  {
    id: "flota.aprobari",
    href: "/flota/aprobari",
    eticheta: "Foi de aprobat",
    zona: "app",
    parinte: "flota",
    fila: "De aprobat",
    featureKey: "fleet",
    permission: "trip_sheets:approve",
    minScope: "team",
    descriere: "Foile de parcurs care așteaptă aprobarea ta.",
  },
  {
    id: "flota.anomalii",
    href: "/flota/anomalii",
    eticheta: "Anomalii de kilometraj",
    zona: "app",
    parinte: "flota",
    fila: "Anomalii de kilometraj",
    featureKey: "fleet",
    permission: "vehicles:update",
    minScope: "team",
    descriere:
      "Kilometrajele care nu se leagă între două foi consecutive, de confirmat sau corectat.",
  },

  // ── Mentenanță ─────────────────────────────────────────────────────────────
  {
    id: "mentenanta",
    href: "/mentenanta",
    eticheta: "Panoul de mentenanță",
    zona: "app",
    parinte: "mentenanta",
    fila: "Panou",
    featureKey: "maintenance",
    permission: "maintenance:read",
    minScope: "own",
    descriere: "Ce e scadent, ce e în lucru și ce sesizări au rămas neatinse.",
  },
  {
    id: "mentenanta.echipamente",
    href: "/mentenanta/echipamente",
    eticheta: "Echipamente",
    zona: "app",
    parinte: "mentenanta",
    fila: "Echipamente",
    featureKey: "maintenance",
    permission: "maintenance:read",
    minScope: "team",
    descriere: "Echipamentele și utilajele aflate în evidență, cu istoricul lor.",
  },
  {
    id: "mentenanta.echipamente.nou",
    href: "/mentenanta/echipamente/nou",
    eticheta: "Echipament nou",
    zona: "app",
    parinte: "mentenanta",
    fila: null,
    featureKey: "maintenance",
    permission: "maintenance:update",
    minScope: "team",
    descriere: "Adăugarea unui echipament în evidență.",
  },
  {
    id: "mentenanta.interventii",
    href: "/mentenanta/interventii",
    eticheta: "Intervenții",
    zona: "app",
    parinte: "mentenanta",
    fila: "Intervenții",
    featureKey: "maintenance",
    permission: "maintenance:read",
    minScope: "team",
    descriere: "Intervențiile de mentenanță efectuate, cu costurile și piesele folosite.",
  },
  {
    id: "mentenanta.planuri",
    href: "/mentenanta/planuri",
    eticheta: "Planuri de mentenanță",
    zona: "app",
    parinte: "mentenanta",
    fila: "Planuri",
    featureKey: "maintenance",
    permission: "maintenance:read",
    minScope: "team",
    descriere: "Mentenanța periodică: la câte ore sau la câte luni se face fiecare operațiune.",
  },
  {
    id: "mentenanta.sesizari",
    href: "/mentenanta/sesizari",
    eticheta: "Sesizări de defecțiune",
    zona: "app",
    parinte: "mentenanta",
    fila: "Sesizări",
    featureKey: "maintenance",
    permission: "maintenance:read",
    minScope: "own",
    descriere: "Defecțiunile raportate de colegi, de preluat și rezolvat.",
  },
  {
    id: "mentenanta.sesizari.noua",
    href: "/mentenanta/sesizari/noua",
    eticheta: "Sesizare nouă",
    zona: "app",
    parinte: "mentenanta",
    fila: null,
    featureKey: "maintenance",
    permission: "maintenance:create",
    minScope: "own",
    descriere: "Raportarea unei defecțiuni la un utilaj sau echipament.",
  },

  // ── Inventar ───────────────────────────────────────────────────────────────
  {
    id: "inventar",
    href: "/inventar",
    eticheta: "Inventar",
    zona: "app",
    parinte: "inventar",
    fila: "Obiecte",
    featureKey: "inventory",
    permission: "inventory:read",
    minScope: "own",
    descriere: "Obiectele de inventar, cui sunt predate și pe ce proces-verbal.",
  },
  {
    id: "inventar.in-primire",
    href: "/inventar/in-primire",
    eticheta: "Ce am în primire",
    zona: "app",
    parinte: "inventar",
    fila: "Ce am în primire",
    featureKey: "inventory",
    permission: "inventory:read",
    minScope: "own",
    descriere: "Obiectele pe care le ai tu în primire, cu procesele-verbale semnate.",
  },

  // ── Anunțuri ───────────────────────────────────────────────────────────────
  {
    id: "anunturi",
    href: "/anunturi",
    eticheta: "Anunțuri",
    zona: "app",
    parinte: "anunturi",
    fila: null,
    featureKey: "announcements",
    permission: "announcements:read",
    minScope: "own",
    descriere: "Avizierul firmei: anunțurile publicate, ciornele și cele programate.",
  },

  // ── Ticketing IT ───────────────────────────────────────────────────────────
  {
    id: "ticketing",
    href: "/ticketing",
    eticheta: "Tichetele mele",
    zona: "app",
    parinte: "ticketing",
    fila: "Tichetele mele",
    featureKey: "ticketing",
    permission: "tickets:read",
    minScope: "own",
    descriere: "Tichetele IT pe care le-ai deschis tu, cu răspunsurile primite.",
  },
  {
    id: "ticketing.nou",
    href: "/ticketing/nou",
    eticheta: "Tichet nou",
    zona: "app",
    parinte: "ticketing",
    fila: "Tichet nou",
    featureKey: "ticketing",
    permission: "tickets:create",
    minScope: "own",
    descriere: "Deschiderea unui tichet către echipa IT.",
  },
  {
    id: "ticketing.coada",
    href: "/ticketing/coada",
    eticheta: "Coada echipei",
    zona: "app",
    parinte: "ticketing",
    fila: "Coada echipei",
    featureKey: "ticketing",
    permission: "tickets:read",
    minScope: "team",
    descriere: "Tichetele IT de preluat și rezolvat, ale întregii echipe.",
  },

  // ── Salarizare ─────────────────────────────────────────────────────────────
  {
    id: "salarizare",
    href: "/salarizare",
    eticheta: "Salarizare",
    zona: "app",
    parinte: "salarizare",
    fila: null,
    featureKey: "payroll",
    permission: "payroll:read",
    minScope: "all",
    descriere:
      "Perioadele de salarizare: calculul lunar, verificarea, fluturașii și închiderea lunii.",
  },
  {
    id: "salarizare.componente",
    href: "/salarizare/componente",
    eticheta: "Sporuri și prime",
    zona: "app",
    parinte: "componente-salariale",
    fila: null,
    featureKey: "payroll",
    permission: "payroll:read",
    minScope: "team",
    descriere: "Sporurile și primele configurate, cu modul lor de calcul.",
  },
  {
    id: "salarizare.popriri",
    href: "/salarizare/popriri",
    eticheta: "Popriri",
    zona: "app",
    parinte: "popriri",
    fila: null,
    featureKey: "payroll",
    permission: "payroll:read",
    minScope: "all",
    descriere: "Popririle pe salarii, cu sumele reținute lunar și soldul rămas.",
  },
  {
    id: "salarizare.istoric",
    href: "/salarizare/istoric-venituri",
    eticheta: "Istoric de venituri",
    zona: "app",
    parinte: "salarizare",
    fila: null,
    featureKey: "payroll",
    permission: "payroll:create",
    minScope: "all",
    descriere: "Veniturile plătite în timp, pe angajat — baza adeverințelor de venit.",
  },
  {
    id: "salarizare.setari",
    href: "/salarizare/setari",
    eticheta: "Setări salarizare",
    zona: "app",
    parinte: "salarizare",
    fila: null,
    featureKey: "payroll",
    permission: "payroll:update",
    minScope: "all",
    descriere: "Parametrii de calcul ai firmei: contribuții, deduceri, zile lucrătoare.",
  },
  {
    id: "rapoarte",
    href: "/rapoarte",
    eticheta: "Rapoarte",
    zona: "app",
    parinte: "rapoarte",
    fila: null,
    featureKey: "payroll",
    permission: "payroll:read",
    minScope: "all",
    descriere: "Rapoartele de personal și salarizare, cu export în Excel.",
  },

  // ── Diurne și deplasări ────────────────────────────────────────────────────
  {
    id: "diurna",
    href: "/diurna",
    eticheta: "Deplasări",
    zona: "app",
    parinte: "diurna",
    fila: "Deplasări",
    featureKey: "per_diem",
    permission: "per_diem:read",
    minScope: "own",
    descriere: "Deplasările înregistrate și diurna cuvenită pe fiecare.",
  },
  {
    id: "diurna.noua",
    href: "/diurna/noua",
    eticheta: "Deplasare nouă",
    zona: "app",
    parinte: "diurna",
    fila: null,
    featureKey: "per_diem",
    permission: "per_diem:create",
    minScope: "own",
    descriere: "Înregistrarea unei deplasări: destinație, perioadă, mijloc de transport.",
  },
  {
    id: "diurna.aprobari",
    href: "/diurna/aprobari",
    eticheta: "Deplasări de aprobat",
    zona: "app",
    parinte: "diurna",
    fila: "De aprobat",
    featureKey: "per_diem",
    permission: "per_diem:approve",
    minScope: "team",
    descriere: "Deplasările și deconturile care așteaptă decizia ta.",
  },
  {
    id: "diurna.politica",
    href: "/diurna/politica",
    eticheta: "Politica de diurnă",
    zona: "app",
    parinte: "diurna",
    fila: "Politica",
    featureKey: "per_diem",
    permission: "per_diem:read",
    minScope: "own",
    descriere: "Sumele de diurnă pe țări și regulile de acordare ale firmei.",
  },

  // ── Setări ─────────────────────────────────────────────────────────────────
  {
    id: "setari.organizatie",
    href: "/setari/organizatie",
    eticheta: "Datele firmei",
    zona: "app",
    parinte: "setari",
    fila: null,
    featureKey: null,
    permission: "organizations:update",
    minScope: "all",
    descriere: "Denumirea, CUI-ul, sediul și sigla firmei.",
  },
  {
    id: "setari.membri",
    href: "/setari/membri",
    eticheta: "Membri și invitații",
    zona: "app",
    parinte: "setari",
    fila: null,
    featureKey: null,
    permission: "users:update",
    minScope: "all",
    descriere: "Conturile care au acces în aplicație, rolurile lor și invitațiile trimise.",
  },
  {
    id: "setari.audit",
    href: "/setari/audit",
    eticheta: "Jurnal de audit",
    zona: "app",
    parinte: "audit",
    fila: null,
    featureKey: null,
    permission: "audit:read",
    minScope: "all",
    descriere: "Cine ce a schimbat și când, cu valoarea dinainte și cea de după.",
  },

  // ── Portalul angajatului ───────────────────────────────────────────────────
  {
    id: "portal",
    href: "/portal",
    eticheta: "Acasă",
    zona: "portal",
    parinte: "portal-acasa",
    fila: null,
    featureKey: null,
    permission: null,
    minScope: "own",
    descriere: "Pagina de start a portalului: ce ai de făcut azi și ce s-a schimbat.",
  },
  {
    id: "portal.pontaj",
    href: "/portal/pontajul-meu",
    eticheta: "Pontajul meu",
    zona: "portal",
    parinte: "portal-pontaj",
    fila: null,
    featureKey: "attendance",
    permission: "attendance:read",
    minScope: "own",
    descriere: "Orele tale pe luna curentă, zi cu zi, cu totalul lunar.",
  },
  {
    id: "portal.pontaj.saptamana",
    href: "/portal/pontajul-meu/saptamana",
    eticheta: "Planul săptămânii",
    zona: "portal",
    parinte: "portal-pontaj",
    fila: null,
    featureKey: "attendance",
    permission: "attendance:create",
    minScope: "own",
    descriere: "Orele planificate pe săptămâna care vine, trimise apoi spre aprobare.",
  },
  {
    id: "portal.ceas",
    href: "/portal/ceas",
    eticheta: "Ceasul de pontare",
    zona: "portal",
    parinte: "portal-pontaj",
    fila: null,
    featureKey: "attendance",
    permission: "attendance:create",
    minScope: "own",
    descriere: "„Am intrat” și „Am ieșit”, dintr-o singură atingere. Trebuie activat din setări.",
  },
  {
    id: "portal.ponteaza",
    href: "/portal/ponteaza",
    eticheta: "Pontare cu cod",
    zona: "portal",
    parinte: "portal-pontaj",
    fila: null,
    featureKey: "attendance",
    permission: "attendance:create",
    minScope: "own",
    descriere: "Pontarea prin codul afișat la punctul de lucru sau prin scanarea afișului.",
  },
  {
    id: "portal.concedii",
    href: "/portal/concediile-mele",
    eticheta: "Concediile mele",
    zona: "portal",
    parinte: "portal-concedii",
    fila: null,
    featureKey: "leave",
    permission: "leave:read",
    minScope: "own",
    descriere: "Cererile tale de concediu, starea fiecăreia și zilele care ți-au rămas.",
  },
  {
    id: "portal.concedii.noua",
    href: "/portal/concediile-mele/noua",
    eticheta: "Cerere de concediu",
    zona: "portal",
    parinte: "portal-concedii",
    fila: null,
    featureKey: "leave",
    permission: "leave:create",
    minScope: "own",
    descriere: "Depunerea unei cereri de concediu: tipul, perioada, motivul.",
  },
  {
    id: "portal.salariu",
    href: "/portal/salariul-meu",
    eticheta: "Salariul meu",
    zona: "portal",
    parinte: "portal-salariul",
    fila: null,
    featureKey: "payroll",
    permission: "payroll:read",
    minScope: "own",
    descriere: "Fluturașii tăi de salariu, lună de lună, cu descărcare în PDF.",
  },
  {
    id: "portal.documente",
    href: "/portal/documentele-mele",
    eticheta: "Documentele mele",
    zona: "portal",
    parinte: "portal-documente",
    fila: null,
    featureKey: "employee_portal",
    permission: "employees:read",
    minScope: "own",
    descriere: "Adeverințele și actele emise pe numele tău, de descărcat.",
  },
  {
    id: "portal.diurna",
    href: "/portal/diurna-mea",
    eticheta: "Diurna mea",
    zona: "portal",
    parinte: "portal-diurna",
    fila: null,
    featureKey: "per_diem",
    permission: "per_diem:read",
    minScope: "own",
    descriere: "Deplasările tale și diurna cuvenită pe fiecare.",
  },
  {
    id: "portal.diurna.noua",
    href: "/portal/diurna-mea/noua",
    eticheta: "Deplasare nouă",
    zona: "portal",
    parinte: "portal-diurna",
    fila: null,
    featureKey: "per_diem",
    permission: "per_diem:create",
    minScope: "own",
    descriere: "Anunțarea unei deplasări, cu destinația și perioada.",
  },
  {
    id: "portal.cursuri",
    href: "/portal/cursurile-mele",
    eticheta: "Cursurile mele",
    zona: "portal",
    parinte: "portal-cursuri",
    fila: null,
    featureKey: "courses",
    permission: "courses:read",
    minScope: "own",
    descriere: "Cursurile care îți sunt atribuite, cu lecțiile și testele lor.",
  },
  {
    id: "portal.integrare",
    href: "/portal/integrarea-mea",
    eticheta: "Integrarea mea",
    zona: "portal",
    parinte: "portal-integrare",
    fila: null,
    featureKey: "onboarding",
    permission: "checklists:read",
    minScope: "own",
    descriere: "Pașii tăi de integrare în firmă și ce mai ai de bifat.",
  },
  {
    id: "portal.instruiri",
    href: "/portal/instruirile-mele",
    eticheta: "Dosarul meu SSM",
    zona: "portal",
    parinte: "portal-instruiri",
    fila: null,
    featureKey: "ssm",
    permission: "ssm:read",
    minScope: "own",
    descriere: "Instruirile tale de securitate, fișa de aptitudine și echipamentul primit.",
  },
  {
    id: "portal.in-primire",
    href: "/portal/in-primirea-mea",
    eticheta: "Ce am în primire",
    zona: "portal",
    parinte: "portal-in-primire",
    fila: null,
    featureKey: "inventory",
    permission: "inventory:read",
    minScope: "own",
    descriere: "Obiectele pe care le ai în primire și procesele-verbale semnate.",
  },
  {
    id: "portal.echipa",
    href: "/portal/echipa-mea",
    eticheta: "Echipa mea",
    zona: "portal",
    parinte: "portal-echipa",
    fila: null,
    featureKey: "nucleu",
    permission: "employees:read",
    minScope: "own",
    descriere: "Colegii din echipa ta, cu datele lor de contact de serviciu.",
  },
  {
    id: "portal.anunturi",
    href: "/portal/anunturi",
    eticheta: "Anunțuri",
    zona: "portal",
    parinte: "portal-anunturi",
    fila: null,
    featureKey: "announcements",
    permission: "announcements:read",
    minScope: "own",
    descriere: "Anunțurile firmei, cele noi marcate ca necitite.",
  },
  {
    id: "portal.sesizari",
    href: "/portal/sesizari",
    eticheta: "Sesizările mele",
    zona: "portal",
    parinte: "portal-sesizari",
    fila: null,
    featureKey: "maintenance",
    permission: "maintenance:read",
    minScope: "own",
    descriere: "Defecțiunile pe care le-ai raportat și stadiul rezolvării.",
  },
  {
    id: "portal.sesizari.noua",
    href: "/portal/sesizari/noua",
    eticheta: "Sesizare nouă",
    zona: "portal",
    parinte: "portal-sesizari",
    fila: null,
    featureKey: "maintenance",
    permission: "maintenance:create",
    minScope: "own",
    descriere: "Raportarea unei defecțiuni la un utilaj sau echipament.",
  },
  {
    id: "portal.tichete",
    href: "/portal/tichetele-mele",
    eticheta: "Tichetele mele",
    zona: "portal",
    parinte: "portal-tichete",
    fila: null,
    featureKey: "ticketing",
    permission: "tickets:read",
    minScope: "own",
    descriere: "Tichetele tale către echipa IT, cu răspunsurile primite.",
  },
  {
    id: "portal.tichete.nou",
    href: "/portal/tichetele-mele/nou",
    eticheta: "Tichet nou",
    zona: "portal",
    parinte: "portal-tichete",
    fila: null,
    featureKey: "ticketing",
    permission: "tickets:create",
    minScope: "own",
    descriere: "Deschiderea unui tichet către echipa IT.",
  },
  {
    id: "portal.notificari",
    href: "/portal/notificarile-mele",
    eticheta: "Notificările mele",
    zona: "portal",
    parinte: null,
    fila: null,
    featureKey: null,
    permission: null,
    minScope: "own",
    descriere: "Tot ce ți s-a notificat, cu legătură către ce a produs fiecare notificare.",
  },
  {
    id: "portal.profil",
    href: "/portal/profilul-meu",
    eticheta: "Profilul meu",
    zona: "portal",
    parinte: null,
    fila: null,
    featureKey: null,
    permission: null,
    minScope: "own",
    descriere: "Datele tale de contact și parola contului.",
  },
];

/*
 * Drumul de click se CALCULEAZĂ din arborele de meniu, nu se scrie.
 *
 * Dacă s-ar scrie de mână, s-ar desincroniza de sidebar la prima reorganizare a
 * meniului, iar asistentul ar dicta cu încredere un drum care nu mai există —
 * mai rău decât niciun drum, fiindcă omul îl caută și nu-l găsește. Aici,
 * mutarea unei intrări dintr-un grup în altul schimbă automat ce spune
 * asistentul.
 */
function calculeazaDrum(intrare: Intrare): readonly string[] {
  const drum: string[] = [];

  if (intrare.zona === "app") {
    const parinte = NAV_ITEMS.find((item) => item.id === intrare.parinte);
    if (parinte !== undefined) {
      const grup = NAV_GROUPS.find((g) => g.id === parinte.group);
      if (grup !== undefined) drum.push(grup.label);
      drum.push(parinte.label);
    }
  } else {
    const parinte = PORTAL_NAV_ITEMS.find((item) => item.id === intrare.parinte);
    if (parinte !== undefined) {
      const grup = PORTAL_NAV_GROUPS.find((g) => g.id === parinte.group);
      if (grup !== undefined) drum.push(grup.label);
      drum.push(parinte.label);
    }
  }

  // Fila e ultimul pas doar dacă spune altceva decât părintele: pe `/pontaj`,
  // părintele e „Pontaj" și fila „Prezența" — două pași reali. Pe `/anunturi`
  // nu există bandă de file, deci drumul se oprește la intrarea de meniu.
  if (intrare.fila !== null && intrare.fila !== drum.at(-1)) drum.push(intrare.fila);

  // O rută fără părinte de meniu (`/profil`, `/notificari`) rămâne cu propria
  // etichetă: e mai bine decât un drum gol, care s-ar randa ca o pastilă mută.
  if (drum.length === 0) drum.push(intrare.eticheta);

  return drum;
}

export const DESTINATII: readonly Destinatie[] = INTRARI.map((intrare) => ({
  ...intrare,
  drum: calculeazaDrum(intrare),
}));

const DUPA_ID: ReadonlyMap<string, Destinatie> = new Map(DESTINATII.map((d) => [d.id, d]));

/** `undefined` pentru un identificator inventat — apelantul îl aruncă tăcut. */
export function destinatiaDupaId(id: string): Destinatie | undefined {
  return DUPA_ID.get(id);
}
