// GENERAT AUTOMAT — nu edita manual.
//
// Regenerare din schema locală:
//   node scripts/gen-types.mjs "postgresql://$USER@localhost:5433/adm_v" > src/types/database.ts
//
// Odată ce proiectul Supabase este conectat, calea preferată devine:
//   pnpm db:types

export type Json = string | number | boolean | null | { [key: string]: Json | undefined } | Json[];

export type Database = {
  public: {
    Tables: {
      audit_logs: {
        Row: {
          id: string;
          organization_id: string | null;
          actor_id: string | null;
          action: Database["public"]["Enums"]["audit_action"];
          status: Database["public"]["Enums"]["audit_status"];
          entity_type: string | null;
          entity_id: string | null;
          before: Json | null;
          after: Json | null;
          ip: string | null;
          user_agent: string | null;
          request_id: string | null;
          error_code: string | null;
          created_at: string;
        };
        Insert: {
          id?: string;
          organization_id?: string | null;
          actor_id?: string | null;
          action: Database["public"]["Enums"]["audit_action"];
          status?: Database["public"]["Enums"]["audit_status"];
          entity_type?: string | null;
          entity_id?: string | null;
          before?: Json | null;
          after?: Json | null;
          ip?: string | null;
          user_agent?: string | null;
          request_id?: string | null;
          error_code?: string | null;
          created_at?: string;
        };
        Update: {
          id?: string;
          organization_id?: string | null;
          actor_id?: string | null;
          action?: Database["public"]["Enums"]["audit_action"];
          status?: Database["public"]["Enums"]["audit_status"];
          entity_type?: string | null;
          entity_id?: string | null;
          before?: Json | null;
          after?: Json | null;
          ip?: string | null;
          user_agent?: string | null;
          request_id?: string | null;
          error_code?: string | null;
          created_at?: string;
        };
        Relationships: [];
      };
      demo_requests: {
        Row: {
          id: string;
          nume: string;
          firma: string;
          email: string;
          telefon: string | null;
          nr_angajati: Database["public"]["Enums"]["employee_band"] | null;
          mesaj: string | null;
          status: Database["public"]["Enums"]["demo_request_status"];
          ip: string | null;
          user_agent: string | null;
          created_at: string;
          created_day: string | null;
          created_by: string | null;
          updated_at: string;
          updated_by: string | null;
          deleted_at: string | null;
        };
        Insert: {
          id?: string;
          nume: string;
          firma: string;
          email: string;
          telefon?: string | null;
          nr_angajati?: Database["public"]["Enums"]["employee_band"] | null;
          mesaj?: string | null;
          status?: Database["public"]["Enums"]["demo_request_status"];
          ip?: string | null;
          user_agent?: string | null;
          created_at?: string;
          created_by?: string | null;
          updated_at?: string;
          updated_by?: string | null;
          deleted_at?: string | null;
        };
        Update: {
          id?: string;
          nume?: string;
          firma?: string;
          email?: string;
          telefon?: string | null;
          nr_angajati?: Database["public"]["Enums"]["employee_band"] | null;
          mesaj?: string | null;
          status?: Database["public"]["Enums"]["demo_request_status"];
          ip?: string | null;
          user_agent?: string | null;
          created_at?: string;
          created_by?: string | null;
          updated_at?: string;
          updated_by?: string | null;
          deleted_at?: string | null;
        };
        Relationships: [];
      };
      departments: {
        Row: {
          id: string;
          organization_id: string;
          parent_id: string | null;
          path: string[];
          depth: number;
          cod: string;
          denumire: string;
          descriere: string | null;
          manager_employee_id: string | null;
          cost_center: string | null;
          activ: boolean;
          created_at: string;
          created_by: string | null;
          updated_at: string;
          updated_by: string | null;
          deleted_at: string | null;
        };
        Insert: {
          id?: string;
          organization_id: string;
          parent_id?: string | null;
          path?: string[];
          depth?: number;
          cod: string;
          denumire: string;
          descriere?: string | null;
          manager_employee_id?: string | null;
          cost_center?: string | null;
          activ?: boolean;
          created_at?: string;
          created_by?: string | null;
          updated_at?: string;
          updated_by?: string | null;
          deleted_at?: string | null;
        };
        Update: {
          id?: string;
          organization_id?: string;
          parent_id?: string | null;
          path?: string[];
          depth?: number;
          cod?: string;
          denumire?: string;
          descriere?: string | null;
          manager_employee_id?: string | null;
          cost_center?: string | null;
          activ?: boolean;
          created_at?: string;
          created_by?: string | null;
          updated_at?: string;
          updated_by?: string | null;
          deleted_at?: string | null;
        };
        Relationships: [];
      };
      document_sequences: {
        Row: {
          id: string;
          organization_id: string;
          document_type: string;
          year: number;
          prefix: string;
          next_number: number;
          padding: number;
          created_at: string;
          created_by: string | null;
          updated_at: string;
          updated_by: string | null;
        };
        Insert: {
          id?: string;
          organization_id: string;
          document_type: string;
          year: number;
          prefix?: string;
          next_number?: number;
          padding?: number;
          created_at?: string;
          created_by?: string | null;
          updated_at?: string;
          updated_by?: string | null;
        };
        Update: {
          id?: string;
          organization_id?: string;
          document_type?: string;
          year?: number;
          prefix?: string;
          next_number?: number;
          padding?: number;
          created_at?: string;
          created_by?: string | null;
          updated_at?: string;
          updated_by?: string | null;
        };
        Relationships: [];
      };
      email_log: {
        Row: {
          id: string;
          organization_id: string | null;
          destinatar: string;
          subiect: string;
          template: string;
          status: Database["public"]["Enums"]["email_status"];
          provider_id: string | null;
          error: string | null;
          sent_at: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          organization_id?: string | null;
          destinatar: string;
          subiect: string;
          template: string;
          status?: Database["public"]["Enums"]["email_status"];
          provider_id?: string | null;
          error?: string | null;
          sent_at?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          organization_id?: string | null;
          destinatar?: string;
          subiect?: string;
          template?: string;
          status?: Database["public"]["Enums"]["email_status"];
          provider_id?: string | null;
          error?: string | null;
          sent_at?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Relationships: [];
      };
      employee_document_types: {
        Row: {
          id: string;
          organization_id: string | null;
          cod: string;
          denumire: string;
          cere_valabilitate: boolean;
          confidential_implicit: boolean;
          vizibil_angajatului_implicit: boolean;
          ordine: number;
          activ: boolean;
          created_at: string;
          created_by: string | null;
          updated_at: string;
          updated_by: string | null;
          deleted_at: string | null;
        };
        Insert: {
          id?: string;
          organization_id?: string | null;
          cod: string;
          denumire: string;
          cere_valabilitate?: boolean;
          confidential_implicit?: boolean;
          vizibil_angajatului_implicit?: boolean;
          ordine?: number;
          activ?: boolean;
          created_at?: string;
          created_by?: string | null;
          updated_at?: string;
          updated_by?: string | null;
          deleted_at?: string | null;
        };
        Update: {
          id?: string;
          organization_id?: string | null;
          cod?: string;
          denumire?: string;
          cere_valabilitate?: boolean;
          confidential_implicit?: boolean;
          vizibil_angajatului_implicit?: boolean;
          ordine?: number;
          activ?: boolean;
          created_at?: string;
          created_by?: string | null;
          updated_at?: string;
          updated_by?: string | null;
          deleted_at?: string | null;
        };
        Relationships: [];
      };
      employee_documents: {
        Row: {
          id: string;
          organization_id: string;
          employee_id: string;
          document_type_id: string;
          contract_id: string | null;
          titlu: string;
          numar_document: string | null;
          data_document: string | null;
          valabil_de_la: string | null;
          valabil_pana: string | null;
          fisier_path: string;
          fisier_nume: string;
          fisier_marime_bytes: number | null;
          fisier_mime: string | null;
          fisier_checksum: string | null;
          confidential: boolean;
          vizibil_angajatului: boolean;
          observatii: string | null;
          created_at: string;
          created_by: string | null;
          updated_at: string;
          updated_by: string | null;
          deleted_at: string | null;
        };
        Insert: {
          id?: string;
          organization_id: string;
          employee_id: string;
          document_type_id: string;
          contract_id?: string | null;
          titlu: string;
          numar_document?: string | null;
          data_document?: string | null;
          valabil_de_la?: string | null;
          valabil_pana?: string | null;
          fisier_path: string;
          fisier_nume: string;
          fisier_marime_bytes?: number | null;
          fisier_mime?: string | null;
          fisier_checksum?: string | null;
          confidential?: boolean;
          vizibil_angajatului?: boolean;
          observatii?: string | null;
          created_at?: string;
          created_by?: string | null;
          updated_at?: string;
          updated_by?: string | null;
          deleted_at?: string | null;
        };
        Update: {
          id?: string;
          organization_id?: string;
          employee_id?: string;
          document_type_id?: string;
          contract_id?: string | null;
          titlu?: string;
          numar_document?: string | null;
          data_document?: string | null;
          valabil_de_la?: string | null;
          valabil_pana?: string | null;
          fisier_path?: string;
          fisier_nume?: string;
          fisier_marime_bytes?: number | null;
          fisier_mime?: string | null;
          fisier_checksum?: string | null;
          confidential?: boolean;
          vizibil_angajatului?: boolean;
          observatii?: string | null;
          created_at?: string;
          created_by?: string | null;
          updated_at?: string;
          updated_by?: string | null;
          deleted_at?: string | null;
        };
        Relationships: [];
      };
      employee_sensitive_data: {
        Row: {
          employee_id: string;
          organization_id: string;
          cnp_ciphertext: string | null;
          cnp_iv: string | null;
          cnp_tag: string | null;
          cnp_key_version: number | null;
          cnp_last4: string | null;
          cnp_hash: string | null;
          iban_ciphertext: string | null;
          iban_iv: string | null;
          iban_tag: string | null;
          iban_key_version: number | null;
          iban_last4: string | null;
          iban_hash: string | null;
          banca: string | null;
          created_at: string;
          created_by: string | null;
          updated_at: string;
          updated_by: string | null;
          deleted_at: string | null;
        };
        Insert: {
          employee_id: string;
          organization_id: string;
          cnp_ciphertext?: string | null;
          cnp_iv?: string | null;
          cnp_tag?: string | null;
          cnp_key_version?: number | null;
          cnp_last4?: string | null;
          cnp_hash?: string | null;
          iban_ciphertext?: string | null;
          iban_iv?: string | null;
          iban_tag?: string | null;
          iban_key_version?: number | null;
          iban_last4?: string | null;
          iban_hash?: string | null;
          banca?: string | null;
          created_at?: string;
          created_by?: string | null;
          updated_at?: string;
          updated_by?: string | null;
          deleted_at?: string | null;
        };
        Update: {
          employee_id?: string;
          organization_id?: string;
          cnp_ciphertext?: string | null;
          cnp_iv?: string | null;
          cnp_tag?: string | null;
          cnp_key_version?: number | null;
          cnp_last4?: string | null;
          cnp_hash?: string | null;
          iban_ciphertext?: string | null;
          iban_iv?: string | null;
          iban_tag?: string | null;
          iban_key_version?: number | null;
          iban_last4?: string | null;
          iban_hash?: string | null;
          banca?: string | null;
          created_at?: string;
          created_by?: string | null;
          updated_at?: string;
          updated_by?: string | null;
          deleted_at?: string | null;
        };
        Relationships: [];
      };
      employee_tax_exemptions: {
        Row: {
          id: string;
          organization_id: string;
          employee_id: string;
          contract_id: string | null;
          exemption_type: Database["public"]["Enums"]["exemption_type"];
          valabil_de_la: string;
          valabil_pana: string | null;
          procent_scutire: number | null;
          plafon_lunar: number | null;
          temei_legal: string | null;
          document_id: string | null;
          observatii: string | null;
          created_at: string;
          created_by: string | null;
          updated_at: string;
          updated_by: string | null;
          deleted_at: string | null;
        };
        Insert: {
          id?: string;
          organization_id: string;
          employee_id: string;
          contract_id?: string | null;
          exemption_type: Database["public"]["Enums"]["exemption_type"];
          valabil_de_la: string;
          valabil_pana?: string | null;
          procent_scutire?: number | null;
          plafon_lunar?: number | null;
          temei_legal?: string | null;
          document_id?: string | null;
          observatii?: string | null;
          created_at?: string;
          created_by?: string | null;
          updated_at?: string;
          updated_by?: string | null;
          deleted_at?: string | null;
        };
        Update: {
          id?: string;
          organization_id?: string;
          employee_id?: string;
          contract_id?: string | null;
          exemption_type?: Database["public"]["Enums"]["exemption_type"];
          valabil_de_la?: string;
          valabil_pana?: string | null;
          procent_scutire?: number | null;
          plafon_lunar?: number | null;
          temei_legal?: string | null;
          document_id?: string | null;
          observatii?: string | null;
          created_at?: string;
          created_by?: string | null;
          updated_at?: string;
          updated_by?: string | null;
          deleted_at?: string | null;
        };
        Relationships: [];
      };
      employees: {
        Row: {
          id: string;
          organization_id: string;
          marca: string;
          first_name: string;
          last_name: string;
          full_name: string | null;
          email_personal: string | null;
          telefon: string | null;
          adresa_strada: string | null;
          adresa_oras: string | null;
          adresa_judet: string | null;
          adresa_cod_postal: string | null;
          adresa_tara: string;
          data_nasterii: string | null;
          gen: Database["public"]["Enums"]["gen"];
          cetatenie: string;
          tip_act_identitate: string | null;
          serie_act: string | null;
          numar_act: string | null;
          act_eliberat_de: string | null;
          act_valabil_pana: string | null;
          department_id: string | null;
          job_position_id: string | null;
          manager_employee_id: string | null;
          manager_path: string[];
          hired_on: string | null;
          terminated_on: string | null;
          conditii_munca: Database["public"]["Enums"]["conditii_munca"];
          grad_handicap: string | null;
          nr_persoane_intretinere: number;
          optiune_pilon_ii: boolean;
          status: Database["public"]["Enums"]["employee_status"];
          user_id: string | null;
          is_primary: boolean;
          contact_urgenta_nume: string | null;
          contact_urgenta_telefon: string | null;
          contact_urgenta_relatie: string | null;
          observatii: string | null;
          created_at: string;
          created_by: string | null;
          updated_at: string;
          updated_by: string | null;
          deleted_at: string | null;
        };
        Insert: {
          id?: string;
          organization_id: string;
          marca: string;
          first_name: string;
          last_name: string;
          email_personal?: string | null;
          telefon?: string | null;
          adresa_strada?: string | null;
          adresa_oras?: string | null;
          adresa_judet?: string | null;
          adresa_cod_postal?: string | null;
          adresa_tara?: string;
          data_nasterii?: string | null;
          gen?: Database["public"]["Enums"]["gen"];
          cetatenie?: string;
          tip_act_identitate?: string | null;
          serie_act?: string | null;
          numar_act?: string | null;
          act_eliberat_de?: string | null;
          act_valabil_pana?: string | null;
          department_id?: string | null;
          job_position_id?: string | null;
          manager_employee_id?: string | null;
          manager_path?: string[];
          hired_on?: string | null;
          terminated_on?: string | null;
          conditii_munca?: Database["public"]["Enums"]["conditii_munca"];
          grad_handicap?: string | null;
          nr_persoane_intretinere?: number;
          optiune_pilon_ii?: boolean;
          status?: Database["public"]["Enums"]["employee_status"];
          user_id?: string | null;
          is_primary?: boolean;
          contact_urgenta_nume?: string | null;
          contact_urgenta_telefon?: string | null;
          contact_urgenta_relatie?: string | null;
          observatii?: string | null;
          created_at?: string;
          created_by?: string | null;
          updated_at?: string;
          updated_by?: string | null;
          deleted_at?: string | null;
        };
        Update: {
          id?: string;
          organization_id?: string;
          marca?: string;
          first_name?: string;
          last_name?: string;
          email_personal?: string | null;
          telefon?: string | null;
          adresa_strada?: string | null;
          adresa_oras?: string | null;
          adresa_judet?: string | null;
          adresa_cod_postal?: string | null;
          adresa_tara?: string;
          data_nasterii?: string | null;
          gen?: Database["public"]["Enums"]["gen"];
          cetatenie?: string;
          tip_act_identitate?: string | null;
          serie_act?: string | null;
          numar_act?: string | null;
          act_eliberat_de?: string | null;
          act_valabil_pana?: string | null;
          department_id?: string | null;
          job_position_id?: string | null;
          manager_employee_id?: string | null;
          manager_path?: string[];
          hired_on?: string | null;
          terminated_on?: string | null;
          conditii_munca?: Database["public"]["Enums"]["conditii_munca"];
          grad_handicap?: string | null;
          nr_persoane_intretinere?: number;
          optiune_pilon_ii?: boolean;
          status?: Database["public"]["Enums"]["employee_status"];
          user_id?: string | null;
          is_primary?: boolean;
          contact_urgenta_nume?: string | null;
          contact_urgenta_telefon?: string | null;
          contact_urgenta_relatie?: string | null;
          observatii?: string | null;
          created_at?: string;
          created_by?: string | null;
          updated_at?: string;
          updated_by?: string | null;
          deleted_at?: string | null;
        };
        Relationships: [];
      };
      employment_contracts: {
        Row: {
          id: string;
          organization_id: string;
          employee_id: string;
          parent_contract_id: string | null;
          este_act_aditional: boolean;
          numar: string;
          data_contract: string;
          valabil_de_la: string;
          valabil_pana: string | null;
          contract_duration: Database["public"]["Enums"]["contract_duration"];
          motiv_determinat: string | null;
          norma_ore_saptamana: number;
          norma_ore_zi: number;
          work_mode: Database["public"]["Enums"]["work_mode"];
          special_regime: Database["public"]["Enums"]["special_regime"] | null;
          loc_telemunca: string | null;
          loc_munca: string | null;
          department_id: string | null;
          job_position_id: string | null;
          conditii_munca: Database["public"]["Enums"]["conditii_munca"];
          salariu_baza: number;
          moneda: string;
          zile_concediu_anual: number;
          perioada_proba_zile: number | null;
          preaviz_zile: number | null;
          status: Database["public"]["Enums"]["contract_status"];
          cod_revisal: string | null;
          fisier_path: string | null;
          motiv_incetare: string | null;
          temei_incetare: string | null;
          incetat_la: string | null;
          created_at: string;
          created_by: string | null;
          updated_at: string;
          updated_by: string | null;
          deleted_at: string | null;
        };
        Insert: {
          id?: string;
          organization_id: string;
          employee_id: string;
          parent_contract_id?: string | null;
          este_act_aditional?: boolean;
          numar: string;
          data_contract: string;
          valabil_de_la: string;
          valabil_pana?: string | null;
          contract_duration?: Database["public"]["Enums"]["contract_duration"];
          motiv_determinat?: string | null;
          norma_ore_saptamana?: number;
          norma_ore_zi?: number;
          work_mode?: Database["public"]["Enums"]["work_mode"];
          special_regime?: Database["public"]["Enums"]["special_regime"] | null;
          loc_telemunca?: string | null;
          loc_munca?: string | null;
          department_id?: string | null;
          job_position_id?: string | null;
          conditii_munca?: Database["public"]["Enums"]["conditii_munca"];
          salariu_baza: number;
          moneda?: string;
          zile_concediu_anual?: number;
          perioada_proba_zile?: number | null;
          preaviz_zile?: number | null;
          status?: Database["public"]["Enums"]["contract_status"];
          cod_revisal?: string | null;
          fisier_path?: string | null;
          motiv_incetare?: string | null;
          temei_incetare?: string | null;
          incetat_la?: string | null;
          created_at?: string;
          created_by?: string | null;
          updated_at?: string;
          updated_by?: string | null;
          deleted_at?: string | null;
        };
        Update: {
          id?: string;
          organization_id?: string;
          employee_id?: string;
          parent_contract_id?: string | null;
          este_act_aditional?: boolean;
          numar?: string;
          data_contract?: string;
          valabil_de_la?: string;
          valabil_pana?: string | null;
          contract_duration?: Database["public"]["Enums"]["contract_duration"];
          motiv_determinat?: string | null;
          norma_ore_saptamana?: number;
          norma_ore_zi?: number;
          work_mode?: Database["public"]["Enums"]["work_mode"];
          special_regime?: Database["public"]["Enums"]["special_regime"] | null;
          loc_telemunca?: string | null;
          loc_munca?: string | null;
          department_id?: string | null;
          job_position_id?: string | null;
          conditii_munca?: Database["public"]["Enums"]["conditii_munca"];
          salariu_baza?: number;
          moneda?: string;
          zile_concediu_anual?: number;
          perioada_proba_zile?: number | null;
          preaviz_zile?: number | null;
          status?: Database["public"]["Enums"]["contract_status"];
          cod_revisal?: string | null;
          fisier_path?: string | null;
          motiv_incetare?: string | null;
          temei_incetare?: string | null;
          incetat_la?: string | null;
          created_at?: string;
          created_by?: string | null;
          updated_at?: string;
          updated_by?: string | null;
          deleted_at?: string | null;
        };
        Relationships: [];
      };
      features: {
        Row: {
          feature_key: string;
          denumire: string;
          descriere: string | null;
          icon: string;
          grup: Database["public"]["Enums"]["feature_group"];
          is_core: boolean;
          sort_order: number;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          feature_key: string;
          denumire: string;
          descriere?: string | null;
          icon?: string;
          grup: Database["public"]["Enums"]["feature_group"];
          is_core?: boolean;
          sort_order?: number;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          feature_key?: string;
          denumire?: string;
          descriere?: string | null;
          icon?: string;
          grup?: Database["public"]["Enums"]["feature_group"];
          is_core?: boolean;
          sort_order?: number;
          created_at?: string;
          updated_at?: string;
        };
        Relationships: [];
      };
      hr_document_templates: {
        Row: {
          id: string;
          organization_id: string | null;
          cod: string;
          denumire: string;
          descriere: string | null;
          continut_html: string;
          variabile: Json;
          serie: string;
          necesita_aprobare: boolean;
          activ: boolean;
          created_at: string;
          created_by: string | null;
          updated_at: string;
          updated_by: string | null;
          deleted_at: string | null;
        };
        Insert: {
          id?: string;
          organization_id?: string | null;
          cod: string;
          denumire: string;
          descriere?: string | null;
          continut_html: string;
          variabile?: Json;
          serie?: string;
          necesita_aprobare?: boolean;
          activ?: boolean;
          created_at?: string;
          created_by?: string | null;
          updated_at?: string;
          updated_by?: string | null;
          deleted_at?: string | null;
        };
        Update: {
          id?: string;
          organization_id?: string | null;
          cod?: string;
          denumire?: string;
          descriere?: string | null;
          continut_html?: string;
          variabile?: Json;
          serie?: string;
          necesita_aprobare?: boolean;
          activ?: boolean;
          created_at?: string;
          created_by?: string | null;
          updated_at?: string;
          updated_by?: string | null;
          deleted_at?: string | null;
        };
        Relationships: [];
      };
      hr_issued_documents: {
        Row: {
          id: string;
          organization_id: string;
          template_id: string | null;
          employee_id: string;
          contract_id: string | null;
          serie: string;
          numar: number;
          numar_afisat: string;
          titlu: string;
          scop: string | null;
          emis_la: string;
          valabil_pana: string | null;
          date_document: Json;
          continut_html: string | null;
          fisier_path: string | null;
          continut_checksum: string;
          cod_verificare: string | null;
          emis_de: string | null;
          anulat_la: string | null;
          motiv_anulare: string | null;
          created_at: string;
          created_by: string | null;
          updated_at: string;
          updated_by: string | null;
          deleted_at: string | null;
        };
        Insert: {
          id?: string;
          organization_id: string;
          template_id?: string | null;
          employee_id: string;
          contract_id?: string | null;
          serie: string;
          numar: number;
          numar_afisat: string;
          titlu: string;
          scop?: string | null;
          emis_la?: string;
          valabil_pana?: string | null;
          date_document?: Json;
          continut_html?: string | null;
          fisier_path?: string | null;
          continut_checksum: string;
          cod_verificare?: string | null;
          emis_de?: string | null;
          anulat_la?: string | null;
          motiv_anulare?: string | null;
          created_at?: string;
          created_by?: string | null;
          updated_at?: string;
          updated_by?: string | null;
          deleted_at?: string | null;
        };
        Update: {
          id?: string;
          organization_id?: string;
          template_id?: string | null;
          employee_id?: string;
          contract_id?: string | null;
          serie?: string;
          numar?: number;
          numar_afisat?: string;
          titlu?: string;
          scop?: string | null;
          emis_la?: string;
          valabil_pana?: string | null;
          date_document?: Json;
          continut_html?: string | null;
          fisier_path?: string | null;
          continut_checksum?: string;
          cod_verificare?: string | null;
          emis_de?: string | null;
          anulat_la?: string | null;
          motiv_anulare?: string | null;
          created_at?: string;
          created_by?: string | null;
          updated_at?: string;
          updated_by?: string | null;
          deleted_at?: string | null;
        };
        Relationships: [];
      };
      invitations: {
        Row: {
          id: string;
          organization_id: string;
          email: string;
          role: Database["public"]["Enums"]["app_role"];
          token_hash: string;
          expires_at: string;
          status: Database["public"]["Enums"]["invitation_status"];
          invited_by: string | null;
          accepted_at: string | null;
          accepted_by: string | null;
          created_at: string;
          created_by: string | null;
          updated_at: string;
          updated_by: string | null;
          deleted_at: string | null;
        };
        Insert: {
          id?: string;
          organization_id: string;
          email: string;
          role?: Database["public"]["Enums"]["app_role"];
          token_hash: string;
          expires_at: string;
          status?: Database["public"]["Enums"]["invitation_status"];
          invited_by?: string | null;
          accepted_at?: string | null;
          accepted_by?: string | null;
          created_at?: string;
          created_by?: string | null;
          updated_at?: string;
          updated_by?: string | null;
          deleted_at?: string | null;
        };
        Update: {
          id?: string;
          organization_id?: string;
          email?: string;
          role?: Database["public"]["Enums"]["app_role"];
          token_hash?: string;
          expires_at?: string;
          status?: Database["public"]["Enums"]["invitation_status"];
          invited_by?: string | null;
          accepted_at?: string | null;
          accepted_by?: string | null;
          created_at?: string;
          created_by?: string | null;
          updated_at?: string;
          updated_by?: string | null;
          deleted_at?: string | null;
        };
        Relationships: [];
      };
      job_descriptions: {
        Row: {
          id: string;
          organization_id: string;
          employee_id: string | null;
          job_position_id: string | null;
          contract_id: string | null;
          versiune: number;
          titlu: string;
          continut: string | null;
          atributii: Json;
          competente: Json;
          subordonare: string | null;
          valabil_de_la: string;
          valabil_pana: string | null;
          fisier_path: string | null;
          semnat_la: string | null;
          semnat_de_angajat: boolean;
          semnatura_ip: string | null;
          activ: boolean;
          created_at: string;
          created_by: string | null;
          updated_at: string;
          updated_by: string | null;
          deleted_at: string | null;
        };
        Insert: {
          id?: string;
          organization_id: string;
          employee_id?: string | null;
          job_position_id?: string | null;
          contract_id?: string | null;
          versiune?: number;
          titlu: string;
          continut?: string | null;
          atributii?: Json;
          competente?: Json;
          subordonare?: string | null;
          valabil_de_la: string;
          valabil_pana?: string | null;
          fisier_path?: string | null;
          semnat_la?: string | null;
          semnat_de_angajat?: boolean;
          semnatura_ip?: string | null;
          activ?: boolean;
          created_at?: string;
          created_by?: string | null;
          updated_at?: string;
          updated_by?: string | null;
          deleted_at?: string | null;
        };
        Update: {
          id?: string;
          organization_id?: string;
          employee_id?: string | null;
          job_position_id?: string | null;
          contract_id?: string | null;
          versiune?: number;
          titlu?: string;
          continut?: string | null;
          atributii?: Json;
          competente?: Json;
          subordonare?: string | null;
          valabil_de_la?: string;
          valabil_pana?: string | null;
          fisier_path?: string | null;
          semnat_la?: string | null;
          semnat_de_angajat?: boolean;
          semnatura_ip?: string | null;
          activ?: boolean;
          created_at?: string;
          created_by?: string | null;
          updated_at?: string;
          updated_by?: string | null;
          deleted_at?: string | null;
        };
        Relationships: [];
      };
      job_positions: {
        Row: {
          id: string;
          organization_id: string;
          cod: string;
          denumire: string;
          cod_cor: string | null;
          nivel_studii: string | null;
          descriere: string | null;
          activ: boolean;
          created_at: string;
          created_by: string | null;
          updated_at: string;
          updated_by: string | null;
          deleted_at: string | null;
        };
        Insert: {
          id?: string;
          organization_id: string;
          cod: string;
          denumire: string;
          cod_cor?: string | null;
          nivel_studii?: string | null;
          descriere?: string | null;
          activ?: boolean;
          created_at?: string;
          created_by?: string | null;
          updated_at?: string;
          updated_by?: string | null;
          deleted_at?: string | null;
        };
        Update: {
          id?: string;
          organization_id?: string;
          cod?: string;
          denumire?: string;
          cod_cor?: string | null;
          nivel_studii?: string | null;
          descriere?: string | null;
          activ?: boolean;
          created_at?: string;
          created_by?: string | null;
          updated_at?: string;
          updated_by?: string | null;
          deleted_at?: string | null;
        };
        Relationships: [];
      };
      notification_preferences: {
        Row: {
          id: string;
          user_id: string;
          organization_id: string;
          kind: Database["public"]["Enums"]["notification_kind"];
          in_app: boolean;
          email: boolean;
          created_at: string;
          created_by: string | null;
          updated_at: string;
          updated_by: string | null;
          deleted_at: string | null;
        };
        Insert: {
          id?: string;
          user_id: string;
          organization_id: string;
          kind: Database["public"]["Enums"]["notification_kind"];
          in_app?: boolean;
          email?: boolean;
          created_at?: string;
          created_by?: string | null;
          updated_at?: string;
          updated_by?: string | null;
          deleted_at?: string | null;
        };
        Update: {
          id?: string;
          user_id?: string;
          organization_id?: string;
          kind?: Database["public"]["Enums"]["notification_kind"];
          in_app?: boolean;
          email?: boolean;
          created_at?: string;
          created_by?: string | null;
          updated_at?: string;
          updated_by?: string | null;
          deleted_at?: string | null;
        };
        Relationships: [];
      };
      notifications: {
        Row: {
          id: string;
          user_id: string;
          organization_id: string;
          kind: Database["public"]["Enums"]["notification_kind"];
          title: string;
          body: string | null;
          link: string | null;
          entity_type: string | null;
          entity_id: string | null;
          read_at: string | null;
          sent_email_at: string | null;
          created_at: string;
          created_by: string | null;
          updated_at: string;
          updated_by: string | null;
          deleted_at: string | null;
        };
        Insert: {
          id?: string;
          user_id: string;
          organization_id: string;
          kind?: Database["public"]["Enums"]["notification_kind"];
          title: string;
          body?: string | null;
          link?: string | null;
          entity_type?: string | null;
          entity_id?: string | null;
          read_at?: string | null;
          sent_email_at?: string | null;
          created_at?: string;
          created_by?: string | null;
          updated_at?: string;
          updated_by?: string | null;
          deleted_at?: string | null;
        };
        Update: {
          id?: string;
          user_id?: string;
          organization_id?: string;
          kind?: Database["public"]["Enums"]["notification_kind"];
          title?: string;
          body?: string | null;
          link?: string | null;
          entity_type?: string | null;
          entity_id?: string | null;
          read_at?: string | null;
          sent_email_at?: string | null;
          created_at?: string;
          created_by?: string | null;
          updated_at?: string;
          updated_by?: string | null;
          deleted_at?: string | null;
        };
        Relationships: [];
      };
      organization_branding: {
        Row: {
          organization_id: string;
          denumire_afisata: string | null;
          primary_color: string | null;
          logo_light_path: string | null;
          logo_dark_path: string | null;
          favicon_path: string | null;
          created_at: string;
          created_by: string | null;
          updated_at: string;
          updated_by: string | null;
          deleted_at: string | null;
        };
        Insert: {
          organization_id: string;
          denumire_afisata?: string | null;
          primary_color?: string | null;
          logo_light_path?: string | null;
          logo_dark_path?: string | null;
          favicon_path?: string | null;
          created_at?: string;
          created_by?: string | null;
          updated_at?: string;
          updated_by?: string | null;
          deleted_at?: string | null;
        };
        Update: {
          organization_id?: string;
          denumire_afisata?: string | null;
          primary_color?: string | null;
          logo_light_path?: string | null;
          logo_dark_path?: string | null;
          favicon_path?: string | null;
          created_at?: string;
          created_by?: string | null;
          updated_at?: string;
          updated_by?: string | null;
          deleted_at?: string | null;
        };
        Relationships: [];
      };
      organization_features: {
        Row: {
          id: string;
          organization_id: string;
          feature_key: string;
          enabled: boolean;
          activated_at: string | null;
          activated_by: string | null;
          settings: Json;
          created_at: string;
          created_by: string | null;
          updated_at: string;
          updated_by: string | null;
          deleted_at: string | null;
        };
        Insert: {
          id?: string;
          organization_id: string;
          feature_key: string;
          enabled?: boolean;
          activated_at?: string | null;
          activated_by?: string | null;
          settings?: Json;
          created_at?: string;
          created_by?: string | null;
          updated_at?: string;
          updated_by?: string | null;
          deleted_at?: string | null;
        };
        Update: {
          id?: string;
          organization_id?: string;
          feature_key?: string;
          enabled?: boolean;
          activated_at?: string | null;
          activated_by?: string | null;
          settings?: Json;
          created_at?: string;
          created_by?: string | null;
          updated_at?: string;
          updated_by?: string | null;
          deleted_at?: string | null;
        };
        Relationships: [];
      };
      organization_members: {
        Row: {
          id: string;
          organization_id: string;
          user_id: string;
          role: Database["public"]["Enums"]["app_role"];
          status: Database["public"]["Enums"]["member_status"];
          job_title: string | null;
          joined_at: string;
          invited_by: string | null;
          invitation_id: string | null;
          deactivated_at: string | null;
          deactivated_by: string | null;
          created_at: string;
          created_by: string | null;
          updated_at: string;
          updated_by: string | null;
          deleted_at: string | null;
        };
        Insert: {
          id?: string;
          organization_id: string;
          user_id: string;
          role?: Database["public"]["Enums"]["app_role"];
          status?: Database["public"]["Enums"]["member_status"];
          job_title?: string | null;
          joined_at?: string;
          invited_by?: string | null;
          invitation_id?: string | null;
          deactivated_at?: string | null;
          deactivated_by?: string | null;
          created_at?: string;
          created_by?: string | null;
          updated_at?: string;
          updated_by?: string | null;
          deleted_at?: string | null;
        };
        Update: {
          id?: string;
          organization_id?: string;
          user_id?: string;
          role?: Database["public"]["Enums"]["app_role"];
          status?: Database["public"]["Enums"]["member_status"];
          job_title?: string | null;
          joined_at?: string;
          invited_by?: string | null;
          invitation_id?: string | null;
          deactivated_at?: string | null;
          deactivated_by?: string | null;
          created_at?: string;
          created_by?: string | null;
          updated_at?: string;
          updated_by?: string | null;
          deleted_at?: string | null;
        };
        Relationships: [];
      };
      organizations: {
        Row: {
          id: string;
          slug: string;
          name: string;
          legal_name: string | null;
          forma_juridica: string | null;
          cui: string;
          cui_normalizat: string | null;
          platitor_tva: boolean;
          reg_com: string | null;
          adresa: string | null;
          judet: string | null;
          oras: string | null;
          cod_postal: string | null;
          tara: string;
          email_contact: string | null;
          telefon_contact: string | null;
          website: string | null;
          reprezentant_legal: string | null;
          status: Database["public"]["Enums"]["organization_status"];
          plan: Database["public"]["Enums"]["plan_type"];
          seats_limit: number;
          subscription_status: Database["public"]["Enums"]["subscription_status_type"];
          trial_ends_at: string | null;
          timezone: string;
          locale: Database["public"]["Enums"]["locale_code"];
          moneda: string;
          activated_at: string | null;
          suspended_at: string | null;
          suspended_reason: string | null;
          created_at: string;
          created_by: string | null;
          updated_at: string;
          updated_by: string | null;
          deleted_at: string | null;
        };
        Insert: {
          id?: string;
          slug: string;
          name: string;
          legal_name?: string | null;
          forma_juridica?: string | null;
          cui: string;
          platitor_tva?: boolean;
          reg_com?: string | null;
          adresa?: string | null;
          judet?: string | null;
          oras?: string | null;
          cod_postal?: string | null;
          tara?: string;
          email_contact?: string | null;
          telefon_contact?: string | null;
          website?: string | null;
          reprezentant_legal?: string | null;
          status?: Database["public"]["Enums"]["organization_status"];
          plan?: Database["public"]["Enums"]["plan_type"];
          seats_limit?: number;
          subscription_status?: Database["public"]["Enums"]["subscription_status_type"];
          trial_ends_at?: string | null;
          timezone?: string;
          locale?: Database["public"]["Enums"]["locale_code"];
          moneda?: string;
          activated_at?: string | null;
          suspended_at?: string | null;
          suspended_reason?: string | null;
          created_at?: string;
          created_by?: string | null;
          updated_at?: string;
          updated_by?: string | null;
          deleted_at?: string | null;
        };
        Update: {
          id?: string;
          slug?: string;
          name?: string;
          legal_name?: string | null;
          forma_juridica?: string | null;
          cui?: string;
          platitor_tva?: boolean;
          reg_com?: string | null;
          adresa?: string | null;
          judet?: string | null;
          oras?: string | null;
          cod_postal?: string | null;
          tara?: string;
          email_contact?: string | null;
          telefon_contact?: string | null;
          website?: string | null;
          reprezentant_legal?: string | null;
          status?: Database["public"]["Enums"]["organization_status"];
          plan?: Database["public"]["Enums"]["plan_type"];
          seats_limit?: number;
          subscription_status?: Database["public"]["Enums"]["subscription_status_type"];
          trial_ends_at?: string | null;
          timezone?: string;
          locale?: Database["public"]["Enums"]["locale_code"];
          moneda?: string;
          activated_at?: string | null;
          suspended_at?: string | null;
          suspended_reason?: string | null;
          created_at?: string;
          created_by?: string | null;
          updated_at?: string;
          updated_by?: string | null;
          deleted_at?: string | null;
        };
        Relationships: [];
      };
      platform_admins: {
        Row: {
          id: string;
          user_id: string;
          granted_by: string | null;
          granted_at: string;
          revoked_at: string | null;
          revoked_by: string | null;
          motiv: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          user_id: string;
          granted_by?: string | null;
          granted_at?: string;
          revoked_at?: string | null;
          revoked_by?: string | null;
          motiv?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          user_id?: string;
          granted_by?: string | null;
          granted_at?: string;
          revoked_at?: string | null;
          revoked_by?: string | null;
          motiv?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Relationships: [];
      };
      profiles: {
        Row: {
          id: string;
          email: string;
          full_name: string | null;
          avatar_path: string | null;
          phone: string | null;
          locale: Database["public"]["Enums"]["locale_code"];
          timezone: string;
          last_seen_at: string | null;
          last_organization_id: string | null;
          created_at: string;
          updated_at: string;
          updated_by: string | null;
          deleted_at: string | null;
        };
        Insert: {
          id: string;
          email: string;
          full_name?: string | null;
          avatar_path?: string | null;
          phone?: string | null;
          locale?: Database["public"]["Enums"]["locale_code"];
          timezone?: string;
          last_seen_at?: string | null;
          last_organization_id?: string | null;
          created_at?: string;
          updated_at?: string;
          updated_by?: string | null;
          deleted_at?: string | null;
        };
        Update: {
          id?: string;
          email?: string;
          full_name?: string | null;
          avatar_path?: string | null;
          phone?: string | null;
          locale?: Database["public"]["Enums"]["locale_code"];
          timezone?: string;
          last_seen_at?: string | null;
          last_organization_id?: string | null;
          created_at?: string;
          updated_at?: string;
          updated_by?: string | null;
          deleted_at?: string | null;
        };
        Relationships: [];
      };
      rate_limits: {
        Row: {
          key: string;
          window_start: string;
          count: number;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          key: string;
          window_start: string;
          count?: number;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          key?: string;
          window_start?: string;
          count?: number;
          created_at?: string;
          updated_at?: string;
        };
        Relationships: [];
      };
      retention_policies: {
        Row: {
          id: string;
          organization_id: string | null;
          entity_type: string;
          retention_months: number;
          anonymize_only: boolean;
          enabled: boolean;
          legal_basis: string | null;
          created_at: string;
          created_by: string | null;
          updated_at: string;
          updated_by: string | null;
          deleted_at: string | null;
        };
        Insert: {
          id?: string;
          organization_id?: string | null;
          entity_type: string;
          retention_months: number;
          anonymize_only?: boolean;
          enabled?: boolean;
          legal_basis?: string | null;
          created_at?: string;
          created_by?: string | null;
          updated_at?: string;
          updated_by?: string | null;
          deleted_at?: string | null;
        };
        Update: {
          id?: string;
          organization_id?: string | null;
          entity_type?: string;
          retention_months?: number;
          anonymize_only?: boolean;
          enabled?: boolean;
          legal_basis?: string | null;
          created_at?: string;
          created_by?: string | null;
          updated_at?: string;
          updated_by?: string | null;
          deleted_at?: string | null;
        };
        Relationships: [];
      };
      revisal_config: {
        Row: {
          id: string;
          organization_id: string | null;
          event_type: Database["public"]["Enums"]["revisal_event_type"];
          termen_zile: number;
          reper: string;
          zile_lucratoare: boolean;
          cod_revisal: string | null;
          descriere: string | null;
          valabil_de_la: string;
          valabil_pana: string | null;
          created_at: string;
          created_by: string | null;
          updated_at: string;
          updated_by: string | null;
          deleted_at: string | null;
        };
        Insert: {
          id?: string;
          organization_id?: string | null;
          event_type: Database["public"]["Enums"]["revisal_event_type"];
          termen_zile: number;
          reper?: string;
          zile_lucratoare?: boolean;
          cod_revisal?: string | null;
          descriere?: string | null;
          valabil_de_la: string;
          valabil_pana?: string | null;
          created_at?: string;
          created_by?: string | null;
          updated_at?: string;
          updated_by?: string | null;
          deleted_at?: string | null;
        };
        Update: {
          id?: string;
          organization_id?: string | null;
          event_type?: Database["public"]["Enums"]["revisal_event_type"];
          termen_zile?: number;
          reper?: string;
          zile_lucratoare?: boolean;
          cod_revisal?: string | null;
          descriere?: string | null;
          valabil_de_la?: string;
          valabil_pana?: string | null;
          created_at?: string;
          created_by?: string | null;
          updated_at?: string;
          updated_by?: string | null;
          deleted_at?: string | null;
        };
        Relationships: [];
      };
      revisal_events: {
        Row: {
          id: string;
          organization_id: string;
          employee_id: string;
          contract_id: string | null;
          event_type: Database["public"]["Enums"]["revisal_event_type"];
          data_evenimentului: string;
          termen_transmitere: string;
          transmis_la: string | null;
          transmis_de: string | null;
          status: Database["public"]["Enums"]["revisal_status"];
          payload: Json;
          export_path: string | null;
          export_checksum: string | null;
          numar_inregistrare: string | null;
          eroare: string | null;
          observatii: string | null;
          created_at: string;
          created_by: string | null;
          updated_at: string;
          updated_by: string | null;
          deleted_at: string | null;
        };
        Insert: {
          id?: string;
          organization_id: string;
          employee_id: string;
          contract_id?: string | null;
          event_type: Database["public"]["Enums"]["revisal_event_type"];
          data_evenimentului: string;
          termen_transmitere: string;
          transmis_la?: string | null;
          transmis_de?: string | null;
          status?: Database["public"]["Enums"]["revisal_status"];
          payload?: Json;
          export_path?: string | null;
          export_checksum?: string | null;
          numar_inregistrare?: string | null;
          eroare?: string | null;
          observatii?: string | null;
          created_at?: string;
          created_by?: string | null;
          updated_at?: string;
          updated_by?: string | null;
          deleted_at?: string | null;
        };
        Update: {
          id?: string;
          organization_id?: string;
          employee_id?: string;
          contract_id?: string | null;
          event_type?: Database["public"]["Enums"]["revisal_event_type"];
          data_evenimentului?: string;
          termen_transmitere?: string;
          transmis_la?: string | null;
          transmis_de?: string | null;
          status?: Database["public"]["Enums"]["revisal_status"];
          payload?: Json;
          export_path?: string | null;
          export_checksum?: string | null;
          numar_inregistrare?: string | null;
          eroare?: string | null;
          observatii?: string | null;
          created_at?: string;
          created_by?: string | null;
          updated_at?: string;
          updated_by?: string | null;
          deleted_at?: string | null;
        };
        Relationships: [];
      };
      role_permissions: {
        Row: {
          id: string;
          organization_id: string | null;
          role: Database["public"]["Enums"]["app_role"];
          resource: string;
          action: string;
          scope: Database["public"]["Enums"]["permission_scope"];
          created_at: string;
          created_by: string | null;
          updated_at: string;
          updated_by: string | null;
          deleted_at: string | null;
        };
        Insert: {
          id?: string;
          organization_id?: string | null;
          role: Database["public"]["Enums"]["app_role"];
          resource: string;
          action: string;
          scope?: Database["public"]["Enums"]["permission_scope"];
          created_at?: string;
          created_by?: string | null;
          updated_at?: string;
          updated_by?: string | null;
          deleted_at?: string | null;
        };
        Update: {
          id?: string;
          organization_id?: string | null;
          role?: Database["public"]["Enums"]["app_role"];
          resource?: string;
          action?: string;
          scope?: Database["public"]["Enums"]["permission_scope"];
          created_at?: string;
          created_by?: string | null;
          updated_at?: string;
          updated_by?: string | null;
          deleted_at?: string | null;
        };
        Relationships: [];
      };
      salary_component_types: {
        Row: {
          id: string;
          organization_id: string | null;
          cod: string;
          denumire: string;
          kind: Database["public"]["Enums"]["salary_component_kind"];
          impozabil: boolean;
          intra_in_baza_cas: boolean;
          intra_in_baza_cass: boolean;
          cod_revisal: string | null;
          ordine: number;
          activ: boolean;
          created_at: string;
          created_by: string | null;
          updated_at: string;
          updated_by: string | null;
          deleted_at: string | null;
        };
        Insert: {
          id?: string;
          organization_id?: string | null;
          cod: string;
          denumire: string;
          kind: Database["public"]["Enums"]["salary_component_kind"];
          impozabil?: boolean;
          intra_in_baza_cas?: boolean;
          intra_in_baza_cass?: boolean;
          cod_revisal?: string | null;
          ordine?: number;
          activ?: boolean;
          created_at?: string;
          created_by?: string | null;
          updated_at?: string;
          updated_by?: string | null;
          deleted_at?: string | null;
        };
        Update: {
          id?: string;
          organization_id?: string | null;
          cod?: string;
          denumire?: string;
          kind?: Database["public"]["Enums"]["salary_component_kind"];
          impozabil?: boolean;
          intra_in_baza_cas?: boolean;
          intra_in_baza_cass?: boolean;
          cod_revisal?: string | null;
          ordine?: number;
          activ?: boolean;
          created_at?: string;
          created_by?: string | null;
          updated_at?: string;
          updated_by?: string | null;
          deleted_at?: string | null;
        };
        Relationships: [];
      };
      salary_components: {
        Row: {
          id: string;
          organization_id: string;
          employee_id: string;
          contract_id: string | null;
          component_type_id: string;
          kind: Database["public"]["Enums"]["salary_component_kind"];
          procent: number | null;
          suma: number | null;
          moneda: string;
          valabil_de_la: string;
          valabil_pana: string | null;
          observatii: string | null;
          created_at: string;
          created_by: string | null;
          updated_at: string;
          updated_by: string | null;
          deleted_at: string | null;
        };
        Insert: {
          id?: string;
          organization_id: string;
          employee_id: string;
          contract_id?: string | null;
          component_type_id: string;
          kind: Database["public"]["Enums"]["salary_component_kind"];
          procent?: number | null;
          suma?: number | null;
          moneda?: string;
          valabil_de_la: string;
          valabil_pana?: string | null;
          observatii?: string | null;
          created_at?: string;
          created_by?: string | null;
          updated_at?: string;
          updated_by?: string | null;
          deleted_at?: string | null;
        };
        Update: {
          id?: string;
          organization_id?: string;
          employee_id?: string;
          contract_id?: string | null;
          component_type_id?: string;
          kind?: Database["public"]["Enums"]["salary_component_kind"];
          procent?: number | null;
          suma?: number | null;
          moneda?: string;
          valabil_de_la?: string;
          valabil_pana?: string | null;
          observatii?: string | null;
          created_at?: string;
          created_by?: string | null;
          updated_at?: string;
          updated_by?: string | null;
          deleted_at?: string | null;
        };
        Relationships: [];
      };
      work_permits: {
        Row: {
          id: string;
          organization_id: string;
          employee_id: string;
          tip_permis: string;
          numar: string;
          emis_de: string | null;
          emis_la: string | null;
          valabil_de_la: string;
          valabil_pana: string;
          numar_pasaport: string | null;
          cetatenie: string;
          document_id: string | null;
          notificat_la: string | null;
          observatii: string | null;
          created_at: string;
          created_by: string | null;
          updated_at: string;
          updated_by: string | null;
          deleted_at: string | null;
        };
        Insert: {
          id?: string;
          organization_id: string;
          employee_id: string;
          tip_permis: string;
          numar: string;
          emis_de?: string | null;
          emis_la?: string | null;
          valabil_de_la: string;
          valabil_pana: string;
          numar_pasaport?: string | null;
          cetatenie: string;
          document_id?: string | null;
          notificat_la?: string | null;
          observatii?: string | null;
          created_at?: string;
          created_by?: string | null;
          updated_at?: string;
          updated_by?: string | null;
          deleted_at?: string | null;
        };
        Update: {
          id?: string;
          organization_id?: string;
          employee_id?: string;
          tip_permis?: string;
          numar?: string;
          emis_de?: string | null;
          emis_la?: string | null;
          valabil_de_la?: string;
          valabil_pana?: string;
          numar_pasaport?: string | null;
          cetatenie?: string;
          document_id?: string | null;
          notificat_la?: string | null;
          observatii?: string | null;
          created_at?: string;
          created_by?: string | null;
          updated_at?: string;
          updated_by?: string | null;
          deleted_at?: string | null;
        };
        Relationships: [];
      };
    };
    Views: {
      [_ in never]: never;
    };
    Functions: {
      accept_invitation: {
        Args: {
          p_token: string;
        };
        Returns: string;
      };
      consume_rate_limit: {
        Args: {
          p_key: string;
          p_limit: unknown;
          p_window_seconds: unknown;
        };
        Returns: boolean;
      };
      hr_read_sensitive: {
        Args: {
          p_employee: string;
        };
        Returns: unknown[];
      };
      hr_write_sensitive: {
        Args: {
          p_employee: string;
          p_cnp_ciphertext?: string | null;
          p_cnp_iv?: string | null;
          p_cnp_tag?: string | null;
          p_cnp_key_version?: unknown | null;
          p_cnp_last4?: string | null;
          p_cnp_hash?: string | null;
          p_iban_ciphertext?: string | null;
          p_iban_iv?: string | null;
          p_iban_tag?: string | null;
          p_iban_key_version?: unknown | null;
          p_iban_last4?: string | null;
          p_iban_hash?: string | null;
          p_banca?: string | null;
        };
        Returns: string;
      };
      log_audit_event: {
        Args: {
          p_action: Database["public"]["Enums"]["audit_action"];
          p_status?: Database["public"]["Enums"]["audit_status"] | null;
          p_organization_id?: string | null;
          p_entity_type?: string | null;
          p_entity_id?: string | null;
          p_before?: Json | null;
          p_after?: Json | null;
          p_ip?: string | null;
          p_user_agent?: string | null;
          p_request_id?: string | null;
          p_error_code?: string | null;
        };
        Returns: string;
      };
      peek_invitation: {
        Args: {
          p_token: string;
        };
        Returns: Json;
      };
      submit_demo_request: {
        Args: {
          p_nume: string;
          p_firma: string;
          p_email: string;
          p_telefon?: string | null;
          p_nr_angajati?: Database["public"]["Enums"]["employee_band"] | null;
          p_mesaj?: string | null;
        };
        Returns: string;
      };
      tg_contracts_validari: {
        Args: Record<PropertyKey, never>;
        Returns: unknown;
      };
      tg_departments_path: {
        Args: Record<PropertyKey, never>;
        Returns: unknown;
      };
      tg_departments_path_cascade: {
        Args: Record<PropertyKey, never>;
        Returns: unknown;
      };
      tg_employees_manager_path: {
        Args: Record<PropertyKey, never>;
        Returns: unknown;
      };
      tg_employees_manager_path_cascade: {
        Args: Record<PropertyKey, never>;
        Returns: unknown;
      };
      tg_employees_validari: {
        Args: Record<PropertyKey, never>;
        Returns: unknown;
      };
      tg_set_updated_at: {
        Args: Record<PropertyKey, never>;
        Returns: unknown;
      };
    };
    Enums: {
      app_role: "super_admin" | "org_admin" | "manager" | "hr" | "employee";
      audit_action: "create" | "update" | "delete" | "restore" | "view" | "export" | "import" | "login" | "logout" | "login_failed" | "password_reset" | "invite_sent" | "invite_accepted" | "invite_revoked" | "member_added" | "member_removed" | "role_changed" | "permission_changed" | "feature_toggled" | "org_created" | "org_activated" | "org_suspended" | "tenant_switch" | "tenant_forged" | "rate_limited" | "email_sent" | "demo_requested" | "impersonation_start" | "impersonation_end";
      audit_status: "success" | "failure" | "denied";
      conditii_munca: "normale" | "deosebite" | "speciale";
      contract_duration: "nedeterminat" | "determinat";
      contract_status: "proiect" | "activ" | "suspendat" | "incetat" | "anulat";
      demo_request_status: "new" | "contacted" | "qualified" | "converted" | "rejected" | "spam";
      email_status: "queued" | "sent" | "delivered" | "bounced" | "complained" | "failed";
      employee_band: "1-9" | "10-49" | "50-249" | "250+";
      employee_status: "candidat" | "activ" | "suspendat" | "preaviz" | "incetat" | "arhivat";
      exemption_type: "it" | "constructii" | "agricultura" | "industrie_alimentara" | "persoana_handicap" | "cercetare_dezvoltare";
      feature_group: "core" | "hr" | "operations" | "finance" | "communication" | "portal";
      gen: "masculin" | "feminin" | "nedeclarat";
      invitation_status: "pending" | "accepted" | "expired" | "revoked";
      locale_code: "ro-RO" | "en-US";
      member_status: "active" | "suspended" | "inactive";
      notification_kind: "info" | "success" | "warning" | "error" | "task" | "reminder" | "approval" | "announcement";
      organization_status: "pending" | "active" | "suspended" | "archived";
      permission_scope: "none" | "own" | "team" | "all";
      plan_type: "trial" | "starter" | "professional" | "enterprise";
      revisal_event_type: "angajare" | "modificare_salariu" | "modificare_functie" | "modificare_norma" | "modificare_durata" | "suspendare" | "reluare_activitate" | "detasare" | "incetare" | "corectie";
      revisal_status: "de_pregatit" | "pregatit" | "transmis" | "confirmat" | "respins" | "anulat";
      salary_component_kind: "spor_procent" | "spor_suma" | "indemnizatie" | "prima_recurenta" | "beneficiu_natura";
      special_regime: "ucenicie" | "internship" | "zilier";
      subscription_status_type: "trialing" | "active" | "past_due" | "canceled" | "expired";
      work_mode: "sediu" | "telemunca" | "domiciliu" | "mixt";
    };
    CompositeTypes: {
      [_ in never]: never;
    };
  };
};

export type Tables<T extends keyof Database["public"]["Tables"]> =
  Database["public"]["Tables"][T]["Row"];
export type Enums<T extends keyof Database["public"]["Enums"]> =
  Database["public"]["Enums"][T];
