/**
 * Diurna în străinătate pe țări — coloana „diurna, categoria I” din anexa la
 * HG 518/1995, forma consolidată din Portalul Legislativ (doc. 7037, istoric de
 * 14 consolidări, ultima modificare la 14-10-2024), descărcată cu `curl` pe
 * 2 oct 2026. Fișierul e GENERAT din tabelul anexei, nu transcris de mână;
 * cinci rânduri sunt verificate separat în test.
 *
 * Categoria I e cea a personalului obișnuit; categoria a II-a, cu sume mai
 * mari, e pentru demnitari (lista e la finalul anexei).
 *
 * Plafonul neimpozabil pentru firmele private e 2,5 × cuantumul, în limita a 3
 * salarii de bază pe lună — Codul fiscal art. 76 alin. (2) lit. k) pct. (ii),
 * forma consolidată (doc. 171282) citită la aceeași dată.
 *
 * NU se citește din `per_diem_country_rates`: rândurile de acolo sunt marcate
 * „orientative, de verificat de jurist” (0015).
 */
export type TaraDiurna = Readonly<{ tara: string; moneda: "EUR" | "USD"; cuantum: number }>;

/** În cenți întregi: `33.33 * 2.5 * 100` dă 8332,4999… în virgulă mobilă, adică 83,32 în loc de 83,33. */
export function plafonNeimpozabil(cuantum: number): number {
  const centi = Math.round(cuantum * 100);
  return Math.round((centi * 5) / 2) / 100;
}

export const DIURNA_EXTERNA_TARI: readonly TaraDiurna[] = [
  { tara: "Afganistan", moneda: "USD", cuantum: 120 },
  { tara: "Africa de Sud (Republica)", moneda: "USD", cuantum: 38 },
  { tara: "Albania", moneda: "EUR", cuantum: 32 },
  { tara: "Algeria", moneda: "USD", cuantum: 32 },
  {
    tara: "Anglia (Regatul Unit al Marii Britanii și Irlandei de Nord)",
    moneda: "EUR",
    cuantum: 35,
  },
  { tara: "Angola", moneda: "USD", cuantum: 32 },
  { tara: "Antigua și Barbuda", moneda: "USD", cuantum: 32 },
  { tara: "Antile", moneda: "USD", cuantum: 32 },
  { tara: "Arabia Saudită", moneda: "USD", cuantum: 38 },
  { tara: "Argentina", moneda: "USD", cuantum: 32 },
  { tara: "Armenia", moneda: "USD", cuantum: 38 },
  { tara: "Australia", moneda: "USD", cuantum: 38 },
  { tara: "Austria", moneda: "EUR", cuantum: 35 },
  { tara: "Azerbaidjan", moneda: "USD", cuantum: 38 },
  { tara: "Bahamas", moneda: "USD", cuantum: 32 },
  { tara: "Bahrain", moneda: "USD", cuantum: 32 },
  { tara: "Bangladesh", moneda: "USD", cuantum: 32 },
  { tara: "Belarus", moneda: "USD", cuantum: 38 },
  { tara: "Belgia", moneda: "EUR", cuantum: 35 },
  { tara: "Benin", moneda: "USD", cuantum: 32 },
  { tara: "Birmania", moneda: "USD", cuantum: 32 },
  { tara: "Bolivia", moneda: "USD", cuantum: 32 },
  { tara: "Bosnia și Herzegovina", moneda: "EUR", cuantum: 32 },
  { tara: "Botswana", moneda: "USD", cuantum: 32 },
  { tara: "Brazilia", moneda: "USD", cuantum: 32 },
  { tara: "Bulgaria", moneda: "EUR", cuantum: 32 },
  { tara: "Burkina Faso", moneda: "USD", cuantum: 32 },
  { tara: "Burundi", moneda: "USD", cuantum: 32 },
  { tara: "Cambodgia", moneda: "USD", cuantum: 32 },
  { tara: "Camerun", moneda: "USD", cuantum: 32 },
  { tara: "Canada", moneda: "USD", cuantum: 38 },
  { tara: "Capul Verde", moneda: "USD", cuantum: 32 },
  { tara: "Cehia (Republica)", moneda: "EUR", cuantum: 35 },
  { tara: "Centrafricană (Republica)", moneda: "USD", cuantum: 32 },
  { tara: "Chile", moneda: "USD", cuantum: 32 },
  { tara: "Chineză (Republica Populară)", moneda: "USD", cuantum: 38 },
  { tara: "Ciad", moneda: "USD", cuantum: 32 },
  { tara: "Cipru", moneda: "EUR", cuantum: 35 },
  { tara: "Coasta de Fildeș", moneda: "USD", cuantum: 32 },
  { tara: "Columbia", moneda: "USD", cuantum: 32 },
  { tara: "Congo", moneda: "USD", cuantum: 32 },
  { tara: "Coreea (RPD)", moneda: "EUR", cuantum: 30 },
  { tara: "Coreea de Sud", moneda: "USD", cuantum: 38 },
  { tara: "Costa Rica", moneda: "USD", cuantum: 32 },
  { tara: "Croația", moneda: "EUR", cuantum: 32 },
  { tara: "Cuba", moneda: "EUR", cuantum: 32 },
  { tara: "Danemarca", moneda: "EUR", cuantum: 35 },
  { tara: "Djibouti", moneda: "USD", cuantum: 32 },
  { tara: "Dominicană (Republica)", moneda: "USD", cuantum: 32 },
  { tara: "Ecuador", moneda: "USD", cuantum: 32 },
  { tara: "Egipt", moneda: "USD", cuantum: 32 },
  { tara: "Elveția", moneda: "EUR", cuantum: 38 },
  { tara: "Emiratele Arabe Unite", moneda: "USD", cuantum: 38 },
  { tara: "Estonia", moneda: "EUR", cuantum: 35 },
  { tara: "Etiopia", moneda: "USD", cuantum: 32 },
  { tara: "Federația Rusă", moneda: "USD", cuantum: 47 },
  { tara: "Fiji", moneda: "USD", cuantum: 38 },
  { tara: "Filipine", moneda: "USD", cuantum: 32 },
  { tara: "Finlanda", moneda: "EUR", cuantum: 35 },
  { tara: "Franța", moneda: "EUR", cuantum: 35 },
  { tara: "Gabon", moneda: "USD", cuantum: 32 },
  { tara: "Gambia", moneda: "USD", cuantum: 32 },
  { tara: "Georgia", moneda: "USD", cuantum: 38 },
  { tara: "Germania", moneda: "EUR", cuantum: 35 },
  { tara: "Ghana", moneda: "USD", cuantum: 32 },
  { tara: "Grecia", moneda: "EUR", cuantum: 35 },
  { tara: "Guatemala", moneda: "USD", cuantum: 32 },
  { tara: "Guineea", moneda: "USD", cuantum: 32 },
  { tara: "Guineea Ecuatorială", moneda: "USD", cuantum: 32 },
  { tara: "Guineea-Bissau", moneda: "USD", cuantum: 32 },
  { tara: "Guyana", moneda: "USD", cuantum: 32 },
  { tara: "Haiti", moneda: "USD", cuantum: 32 },
  { tara: "Honduras", moneda: "USD", cuantum: 32 },
  { tara: "Hong Kong", moneda: "USD", cuantum: 53 },
  { tara: "India", moneda: "USD", cuantum: 32 },
  { tara: "Indonezia", moneda: "USD", cuantum: 38 },
  { tara: "Iordania", moneda: "USD", cuantum: 38 },
  { tara: "Irak", moneda: "USD", cuantum: 60 },
  { tara: "Iran", moneda: "USD", cuantum: 38 },
  { tara: "Irlanda", moneda: "EUR", cuantum: 35 },
  { tara: "Islanda", moneda: "EUR", cuantum: 35 },
  { tara: "Israel", moneda: "USD", cuantum: 38 },
  { tara: "Italia", moneda: "EUR", cuantum: 35 },
  { tara: "Jamaica", moneda: "USD", cuantum: 32 },
  { tara: "Japonia", moneda: "USD", cuantum: 53 },
  { tara: "Kazahstan", moneda: "USD", cuantum: 38 },
  { tara: "Kârgâzstan", moneda: "USD", cuantum: 38 },
  { tara: "Kenya", moneda: "USD", cuantum: 32 },
  { tara: "Kuwait", moneda: "USD", cuantum: 38 },
  { tara: "Laos", moneda: "USD", cuantum: 32 },
  { tara: "Lesotho", moneda: "USD", cuantum: 32 },
  { tara: "Letonia", moneda: "EUR", cuantum: 35 },
  { tara: "Liban", moneda: "USD", cuantum: 38 },
  { tara: "Liberia", moneda: "USD", cuantum: 32 },
  { tara: "Libia", moneda: "USD", cuantum: 38 },
  { tara: "Lituania", moneda: "EUR", cuantum: 35 },
  { tara: "Luxemburg", moneda: "EUR", cuantum: 35 },
  { tara: "Macedonia", moneda: "EUR", cuantum: 32 },
  { tara: "Madagascar", moneda: "USD", cuantum: 32 },
  { tara: "Malaysia", moneda: "USD", cuantum: 32 },
  { tara: "Mali", moneda: "USD", cuantum: 32 },
  { tara: "Malta", moneda: "EUR", cuantum: 35 },
  { tara: "Maroc", moneda: "USD", cuantum: 32 },
  { tara: "Mauritania", moneda: "USD", cuantum: 32 },
  { tara: "Mauritius", moneda: "USD", cuantum: 32 },
  { tara: "Mexic", moneda: "USD", cuantum: 38 },
  { tara: "Moldova", moneda: "USD", cuantum: 38 },
  { tara: "Mongolia", moneda: "USD", cuantum: 38 },
  { tara: "Mozambic", moneda: "USD", cuantum: 32 },
  { tara: "Muntenegru", moneda: "EUR", cuantum: 32 },
  { tara: "Myanmar", moneda: "USD", cuantum: 32 },
  { tara: "Namibia", moneda: "USD", cuantum: 32 },
  { tara: "Nepal", moneda: "USD", cuantum: 32 },
  { tara: "Nicaragua", moneda: "USD", cuantum: 32 },
  { tara: "Niger", moneda: "USD", cuantum: 32 },
  { tara: "Nigeria", moneda: "USD", cuantum: 32 },
  { tara: "Norvegia", moneda: "EUR", cuantum: 35 },
  { tara: "Noua Zeelandă", moneda: "USD", cuantum: 38 },
  { tara: "Olanda", moneda: "EUR", cuantum: 35 },
  { tara: "Oman", moneda: "USD", cuantum: 38 },
  { tara: "Pakistan", moneda: "USD", cuantum: 32 },
  { tara: "Panama", moneda: "USD", cuantum: 32 },
  { tara: "Papua-Noua Guinee", moneda: "USD", cuantum: 32 },
  { tara: "Paraguay", moneda: "USD", cuantum: 32 },
  { tara: "Peru", moneda: "USD", cuantum: 32 },
  { tara: "Polonia", moneda: "EUR", cuantum: 35 },
  { tara: "Portugalia", moneda: "EUR", cuantum: 35 },
  { tara: "Qatar", moneda: "USD", cuantum: 38 },
  { tara: "Rwanda", moneda: "USD", cuantum: 32 },
  { tara: "S.U.A.", moneda: "USD", cuantum: 53 },
  { tara: "Salvador", moneda: "USD", cuantum: 32 },
  { tara: "San Marino", moneda: "EUR", cuantum: 35 },
  { tara: "Sao Tome și Principe", moneda: "USD", cuantum: 32 },
  { tara: "Senegal", moneda: "USD", cuantum: 32 },
  { tara: "Serbia", moneda: "EUR", cuantum: 32 },
  { tara: "Sierra Leone", moneda: "USD", cuantum: 32 },
  { tara: "Singapore", moneda: "USD", cuantum: 38 },
  { tara: "Siria", moneda: "USD", cuantum: 38 },
  { tara: "Slovacia", moneda: "EUR", cuantum: 35 },
  { tara: "Slovenia", moneda: "EUR", cuantum: 35 },
  { tara: "Somalia", moneda: "USD", cuantum: 32 },
  { tara: "Spania", moneda: "EUR", cuantum: 35 },
  { tara: "Sri Lanka", moneda: "USD", cuantum: 38 },
  { tara: "Sudan", moneda: "USD", cuantum: 32 },
  { tara: "Suedia", moneda: "EUR", cuantum: 35 },
  { tara: "Surinam", moneda: "USD", cuantum: 32 },
  { tara: "Tadjikistan", moneda: "USD", cuantum: 38 },
  { tara: "Taiwan", moneda: "USD", cuantum: 38 },
  { tara: "Tanzania", moneda: "USD", cuantum: 32 },
  { tara: "Thailanda", moneda: "USD", cuantum: 38 },
  { tara: "Togo", moneda: "USD", cuantum: 32 },
  { tara: "Tunisia", moneda: "USD", cuantum: 32 },
  { tara: "Turcia", moneda: "USD", cuantum: 38 },
  { tara: "Turkmenistan", moneda: "USD", cuantum: 38 },
  { tara: "Ucraina", moneda: "USD", cuantum: 38 },
  { tara: "Uganda", moneda: "USD", cuantum: 32 },
  { tara: "Ungaria", moneda: "EUR", cuantum: 35 },
  { tara: "Uruguay", moneda: "USD", cuantum: 32 },
  { tara: "Uzbekistan", moneda: "USD", cuantum: 38 },
  { tara: "Vatican", moneda: "EUR", cuantum: 35 },
  { tara: "Venezuela", moneda: "USD", cuantum: 32 },
  { tara: "Vietnam", moneda: "USD", cuantum: 32 },
  { tara: "Yemen", moneda: "USD", cuantum: 38 },
  { tara: "Zair", moneda: "USD", cuantum: 32 },
  { tara: "Zambia", moneda: "USD", cuantum: 32 },
  { tara: "Zimbabwe", moneda: "USD", cuantum: 32 },
];
